export interface ItalianoCard {
  id: string
  en: string
  it: string
  cat: string
}

function toSlug(s: string): string {
  return s
    .replace(/[àáâ]/g, 'a').replace(/[èéê]/g, 'e').replace(/[ìíî]/g, 'i')
    .replace(/[òóô]/g, 'o').replace(/[ùúû]/g, 'u')
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

const CARDS_RAW: Omit<ItalianoCard, 'id'>[] = [
  // greetings
  { en: 'hello / bye', it: 'ciao', cat: 'greetings' },
  { en: 'good morning', it: 'buongiorno', cat: 'greetings' },
  { en: 'good evening', it: 'buonasera', cat: 'greetings' },
  { en: 'good night', it: 'buonanotte', cat: 'greetings' },
  { en: 'goodbye', it: 'arrivederci', cat: 'greetings' },
  { en: 'thank you', it: 'grazie', cat: 'greetings' },
  { en: 'thank you very much', it: 'grazie mille', cat: 'greetings' },
  { en: 'please', it: 'per favore', cat: 'greetings' },
  { en: "you're welcome", it: 'prego', cat: 'greetings' },
  { en: 'excuse me (informal)', it: 'scusa', cat: 'greetings' },
  { en: 'excuse me (formal)', it: 'scusi', cat: 'greetings' },
  { en: "I'm sorry", it: 'mi dispiace', cat: 'greetings' },
  { en: 'yes', it: 'sì', cat: 'greetings' },
  { en: 'no', it: 'no', cat: 'greetings' },
  { en: 'how are you? (informal)', it: 'come stai?', cat: 'greetings' },
  { en: 'fine, thanks', it: 'bene, grazie', cat: 'greetings' },
  { en: "what's your name?", it: 'come ti chiami?', cat: 'greetings' },
  { en: 'my name is…', it: 'mi chiamo…', cat: 'greetings' },
  { en: 'pleased to meet you', it: 'piacere', cat: 'greetings' },
  // pronouns
  { en: 'I', it: 'io', cat: 'pronouns' },
  { en: 'you (singular, informal)', it: 'tu', cat: 'pronouns' },
  { en: 'you (singular, formal)', it: 'Lei', cat: 'pronouns' },
  { en: 'he', it: 'lui', cat: 'pronouns' },
  { en: 'she', it: 'lei', cat: 'pronouns' },
  { en: 'we', it: 'noi', cat: 'pronouns' },
  { en: 'you (plural)', it: 'voi', cat: 'pronouns' },
  { en: 'they', it: 'loro', cat: 'pronouns' },
  // questions
  { en: 'who', it: 'chi', cat: 'questions' },
  { en: 'what', it: 'cosa', cat: 'questions' },
  { en: 'where', it: 'dove', cat: 'questions' },
  { en: 'when', it: 'quando', cat: 'questions' },
  { en: 'how', it: 'come', cat: 'questions' },
  { en: 'why / because', it: 'perché', cat: 'questions' },
  { en: 'how much (m)', it: 'quanto', cat: 'questions' },
  { en: 'how many (m)', it: 'quanti', cat: 'questions' },
  { en: 'which', it: 'quale', cat: 'questions' },
  // verbs
  { en: 'to be (permanent)', it: 'essere', cat: 'verbs' },
  { en: 'to be / stay (temporary)', it: 'stare', cat: 'verbs' },
  { en: 'to have', it: 'avere', cat: 'verbs' },
  { en: 'to do / make', it: 'fare', cat: 'verbs' },
  { en: 'to say / tell', it: 'dire', cat: 'verbs' },
  { en: 'to go', it: 'andare', cat: 'verbs' },
  { en: 'to come', it: 'venire', cat: 'verbs' },
  { en: 'to know (a fact)', it: 'sapere', cat: 'verbs' },
  { en: 'to know (a person)', it: 'conoscere', cat: 'verbs' },
  { en: 'to want', it: 'volere', cat: 'verbs' },
  { en: 'to be able to / can', it: 'potere', cat: 'verbs' },
  { en: 'to have to / must', it: 'dovere', cat: 'verbs' },
  { en: 'to give', it: 'dare', cat: 'verbs' },
  { en: 'to see', it: 'vedere', cat: 'verbs' },
  { en: 'to hear / feel', it: 'sentire', cat: 'verbs' },
  { en: 'to speak', it: 'parlare', cat: 'verbs' },
  { en: 'to eat', it: 'mangiare', cat: 'verbs' },
  { en: 'to drink', it: 'bere', cat: 'verbs' },
  { en: 'to understand', it: 'capire', cat: 'verbs' },
  { en: 'to read', it: 'leggere', cat: 'verbs' },
  { en: 'to write', it: 'scrivere', cat: 'verbs' },
  { en: 'to sleep', it: 'dormire', cat: 'verbs' },
  { en: 'to work', it: 'lavorare', cat: 'verbs' },
  { en: 'to live (reside)', it: 'abitare', cat: 'verbs' },
  { en: 'to take', it: 'prendere', cat: 'verbs' },
  // nouns
  { en: 'house / home', it: 'la casa', cat: 'nouns' },
  { en: 'time / weather', it: 'il tempo', cat: 'nouns' },
  { en: 'person', it: 'la persona', cat: 'nouns' },
  { en: 'man', it: "l'uomo", cat: 'nouns' },
  { en: 'woman', it: 'la donna', cat: 'nouns' },
  { en: 'child', it: 'il bambino', cat: 'nouns' },
  { en: 'day', it: 'il giorno', cat: 'nouns' },
  { en: 'year', it: "l'anno", cat: 'nouns' },
  { en: 'thing', it: 'la cosa', cat: 'nouns' },
  { en: 'country / village', it: 'il paese', cat: 'nouns' },
  { en: 'city', it: 'la città', cat: 'nouns' },
  { en: 'work / job', it: 'il lavoro', cat: 'nouns' },
  { en: 'book', it: 'il libro', cat: 'nouns' },
  { en: 'word', it: 'la parola', cat: 'nouns' },
  { en: 'problem', it: 'il problema', cat: 'nouns' },
  { en: 'life', it: 'la vita', cat: 'nouns' },
  { en: 'world', it: 'il mondo', cat: 'nouns' },
  { en: 'food', it: 'il cibo', cat: 'nouns' },
  { en: 'water', it: "l'acqua", cat: 'nouns' },
  { en: 'wine', it: 'il vino', cat: 'nouns' },
  { en: 'friend', it: "l'amico", cat: 'nouns' },
  { en: 'family', it: 'la famiglia', cat: 'nouns' },
  { en: 'place / seat', it: 'il posto', cat: 'nouns' },
  { en: 'name', it: 'il nome', cat: 'nouns' },
  { en: 'money', it: 'i soldi', cat: 'nouns' },
  // descriptors
  { en: 'big / great', it: 'grande', cat: 'descriptors' },
  { en: 'small', it: 'piccolo/piccola', cat: 'descriptors' },
  { en: 'beautiful / nice', it: 'bello/bella', cat: 'descriptors' },
  { en: 'ugly / bad', it: 'brutto/brutta', cat: 'descriptors' },
  { en: 'good', it: 'buono/buona', cat: 'descriptors' },
  { en: 'bad / naughty', it: 'cattivo/cattiva', cat: 'descriptors' },
  { en: 'new', it: 'nuovo/nuova', cat: 'descriptors' },
  { en: 'old', it: 'vecchio/vecchia', cat: 'descriptors' },
  { en: 'long', it: 'lungo/lunga', cat: 'descriptors' },
  { en: 'short', it: 'corto/corta', cat: 'descriptors' },
  { en: 'tall / high', it: 'alto/alta', cat: 'descriptors' },
  { en: 'hot / warm', it: 'caldo/calda', cat: 'descriptors' },
  { en: 'cold', it: 'freddo/fredda', cat: 'descriptors' },
  { en: 'strong', it: 'forte', cat: 'descriptors' },
  { en: 'difficult', it: 'difficile', cat: 'descriptors' },
  { en: 'easy', it: 'facile', cat: 'descriptors' },
  { en: 'tired', it: 'stanco/stanca', cat: 'descriptors' },
  { en: 'happy', it: 'felice', cat: 'descriptors' },
  { en: 'sad', it: 'triste', cat: 'descriptors' },
  { en: 'fast', it: 'veloce', cat: 'descriptors' },
  // numbers
  { en: 'zero', it: 'zero', cat: 'numbers' },
  { en: 'one', it: 'uno', cat: 'numbers' },
  { en: 'two', it: 'due', cat: 'numbers' },
  { en: 'three', it: 'tre', cat: 'numbers' },
  { en: 'four', it: 'quattro', cat: 'numbers' },
  { en: 'five', it: 'cinque', cat: 'numbers' },
  { en: 'six', it: 'sei', cat: 'numbers' },
  { en: 'seven', it: 'sette', cat: 'numbers' },
  { en: 'eight', it: 'otto', cat: 'numbers' },
  { en: 'nine', it: 'nove', cat: 'numbers' },
  { en: 'ten', it: 'dieci', cat: 'numbers' },
  { en: 'eleven', it: 'undici', cat: 'numbers' },
  { en: 'twelve', it: 'dodici', cat: 'numbers' },
  { en: 'thirteen', it: 'tredici', cat: 'numbers' },
  { en: 'fourteen', it: 'quattordici', cat: 'numbers' },
  { en: 'fifteen', it: 'quindici', cat: 'numbers' },
  { en: 'sixteen', it: 'sedici', cat: 'numbers' },
  { en: 'seventeen', it: 'diciassette', cat: 'numbers' },
  { en: 'eighteen', it: 'diciotto', cat: 'numbers' },
  { en: 'nineteen', it: 'diciannove', cat: 'numbers' },
  { en: 'twenty', it: 'venti', cat: 'numbers' },
  { en: 'thirty', it: 'trenta', cat: 'numbers' },
  { en: 'forty', it: 'quaranta', cat: 'numbers' },
  { en: 'fifty', it: 'cinquanta', cat: 'numbers' },
  { en: 'one hundred', it: 'cento', cat: 'numbers' },
  { en: 'one thousand', it: 'mille', cat: 'numbers' },
  // colours
  { en: 'red', it: 'rosso/rossa', cat: 'colours' },
  { en: 'blue', it: 'blu', cat: 'colours' },
  { en: 'light blue', it: 'azzurro/azzurra', cat: 'colours' },
  { en: 'green', it: 'verde', cat: 'colours' },
  { en: 'yellow', it: 'giallo/gialla', cat: 'colours' },
  { en: 'orange', it: 'arancione', cat: 'colours' },
  { en: 'purple', it: 'viola', cat: 'colours' },
  { en: 'pink', it: 'rosa', cat: 'colours' },
  { en: 'white', it: 'bianco/bianca', cat: 'colours' },
  { en: 'black', it: 'nero/nera', cat: 'colours' },
  { en: 'grey', it: 'grigio/grigia', cat: 'colours' },
  { en: 'brown', it: 'marrone', cat: 'colours' },
  // shapes
  { en: 'circle', it: 'il cerchio', cat: 'shapes' },
  { en: 'square', it: 'il quadrato', cat: 'shapes' },
  { en: 'rectangle', it: 'il rettangolo', cat: 'shapes' },
  { en: 'triangle', it: 'il triangolo', cat: 'shapes' },
  { en: 'oval', it: "l'ovale", cat: 'shapes' },
  { en: 'star', it: 'la stella', cat: 'shapes' },
  { en: 'heart', it: 'il cuore', cat: 'shapes' },
  // days
  { en: 'Monday', it: 'lunedì', cat: 'days' },
  { en: 'Tuesday', it: 'martedì', cat: 'days' },
  { en: 'Wednesday', it: 'mercoledì', cat: 'days' },
  { en: 'Thursday', it: 'giovedì', cat: 'days' },
  { en: 'Friday', it: 'venerdì', cat: 'days' },
  { en: 'Saturday', it: 'sabato', cat: 'days' },
  { en: 'Sunday', it: 'domenica', cat: 'days' },
  // months
  { en: 'January', it: 'gennaio', cat: 'months' },
  { en: 'February', it: 'febbraio', cat: 'months' },
  { en: 'March', it: 'marzo', cat: 'months' },
  { en: 'April', it: 'aprile', cat: 'months' },
  { en: 'May', it: 'maggio', cat: 'months' },
  { en: 'June', it: 'giugno', cat: 'months' },
  { en: 'July', it: 'luglio', cat: 'months' },
  { en: 'August', it: 'agosto', cat: 'months' },
  { en: 'September', it: 'settembre', cat: 'months' },
  { en: 'October', it: 'ottobre', cat: 'months' },
  { en: 'November', it: 'novembre', cat: 'months' },
  { en: 'December', it: 'dicembre', cat: 'months' },
  // body
  { en: 'head', it: 'la testa', cat: 'body' },
  { en: 'face', it: 'il viso', cat: 'body' },
  { en: 'eye', it: "l'occhio", cat: 'body' },
  { en: 'nose', it: 'il naso', cat: 'body' },
  { en: 'mouth', it: 'la bocca', cat: 'body' },
  { en: 'ear', it: "l'orecchio", cat: 'body' },
  { en: 'neck', it: 'il collo', cat: 'body' },
  { en: 'shoulder', it: 'la spalla', cat: 'body' },
  { en: 'arm', it: 'il braccio', cat: 'body' },
  { en: 'hand', it: 'la mano', cat: 'body' },
  { en: 'finger', it: 'il dito', cat: 'body' },
  { en: 'chest', it: 'il petto', cat: 'body' },
  { en: 'stomach', it: 'lo stomaco', cat: 'body' },
  { en: 'back', it: 'la schiena', cat: 'body' },
  { en: 'leg', it: 'la gamba', cat: 'body' },
  { en: 'knee', it: 'il ginocchio', cat: 'body' },
  { en: 'foot', it: 'il piede', cat: 'body' },
  { en: 'heart', it: 'il cuore', cat: 'body' },
  // time
  { en: 'now', it: 'adesso', cat: 'time' },
  { en: 'today', it: 'oggi', cat: 'time' },
  { en: 'yesterday', it: 'ieri', cat: 'time' },
  { en: 'tomorrow', it: 'domani', cat: 'time' },
  { en: 'morning', it: 'la mattina', cat: 'time' },
  { en: 'afternoon', it: 'il pomeriggio', cat: 'time' },
  { en: 'evening', it: 'la sera', cat: 'time' },
  { en: 'night', it: 'la notte', cat: 'time' },
  { en: 'early / soon', it: 'presto', cat: 'time' },
  { en: 'late', it: 'tardi', cat: 'time' },
  { en: 'always', it: 'sempre', cat: 'time' },
  { en: 'never', it: 'mai', cat: 'time' },
  { en: 'often', it: 'spesso', cat: 'time' },
  { en: 'sometimes', it: 'a volte', cat: 'time' },
  { en: 'already', it: 'già', cat: 'time' },
  { en: 'still / again', it: 'ancora', cat: 'time' },
  { en: 'immediately', it: 'subito', cat: 'time' },
  // particles
  { en: 'of / from / about', it: 'di', cat: 'particles' },
  { en: 'to / at', it: 'a', cat: 'particles' },
  { en: 'from / by / since', it: 'da', cat: 'particles' },
  { en: 'in / into / to', it: 'in', cat: 'particles' },
  { en: 'with', it: 'con', cat: 'particles' },
  { en: 'on / over / about', it: 'su', cat: 'particles' },
  { en: 'for / in order to', it: 'per', cat: 'particles' },
  { en: 'between / among', it: 'tra', cat: 'particles' },
  { en: 'that / which / who', it: 'che', cat: 'particles' },
  { en: 'not', it: 'non', cat: 'particles' },
  { en: 'and', it: 'e', cat: 'particles' },
  { en: 'but', it: 'ma', cat: 'particles' },
  { en: 'also / too', it: 'anche', cat: 'particles' },
  { en: 'very / much', it: 'molto', cat: 'particles' },
  { en: 'more', it: 'più', cat: 'particles' },
  { en: 'less', it: 'meno', cat: 'particles' },
  { en: 'here', it: 'qui', cat: 'particles' },
  { en: 'there', it: 'lì', cat: 'particles' },
  // sentences
  { en: "I don't understand.", it: 'Non capisco.', cat: 'sentences' },
  { en: "I don't know.", it: 'Non lo so.', cat: 'sentences' },
  { en: 'Can you repeat?', it: 'Puoi ripetere?', cat: 'sentences' },
  { en: 'Can you speak more slowly?', it: 'Puoi parlare più lentamente?', cat: 'sentences' },
  { en: 'How do you say… in Italian?', it: 'Come si dice… in italiano?', cat: 'sentences' },
  { en: 'What does… mean?', it: 'Cosa vuol dire…?', cat: 'sentences' },
  { en: 'Do you speak English?', it: 'Parli inglese?', cat: 'sentences' },
  { en: "I'm learning Italian.", it: "Sto imparando l'italiano.", cat: 'sentences' },
  { en: 'I would like…', it: 'Vorrei…', cat: 'sentences' },
  { en: "I'm hungry.", it: 'Ho fame.', cat: 'sentences' },
  { en: "I'm thirsty.", it: 'Ho sete.', cat: 'sentences' },
  { en: "I'm hot.", it: 'Ho caldo.', cat: 'sentences' },
  { en: "I'm cold.", it: 'Ho freddo.', cat: 'sentences' },
  { en: 'I need help.', it: 'Ho bisogno di aiuto.', cat: 'sentences' },
  { en: "I'm fine / I'm well.", it: 'Sto bene.', cat: 'sentences' },
  { en: "I don't feel well.", it: 'Non mi sento bene.', cat: 'sentences' },
  { en: 'Where is the bathroom?', it: "Dov'è il bagno?", cat: 'sentences' },
  { en: 'At what time…?', it: 'A che ora…?', cat: 'sentences' },
  { en: 'Can I have the bill?', it: 'Posso avere il conto?', cat: 'sentences' },
  { en: "I'm allergic to…", it: 'Sono allergico/a a…', cat: 'sentences' },
  { en: "I'm vegetarian.", it: 'Sono vegetariano/a.', cat: 'sentences' },
  { en: 'What time is it?', it: 'Che ore sono?', cat: 'sentences' },
  { en: "I'm from…", it: 'Sono di…', cat: 'sentences' },
  { en: 'I live in…', it: 'Abito a…', cat: 'sentences' },
  { en: 'How old are you?', it: 'Quanti anni hai?', cat: 'sentences' },
  { en: 'I am… years old.', it: 'Ho… anni.', cat: 'sentences' },
  { en: 'Do you like…?', it: 'Ti piace…?', cat: 'sentences' },
  { en: 'I like it a lot.', it: 'Mi piace molto.', cat: 'sentences' },
  { en: "I don't like it.", it: 'Non mi piace.', cat: 'sentences' },
  { en: "It's delicious!", it: 'È delizioso!', cat: 'sentences' },
  { en: 'How beautiful!', it: 'Che bello!', cat: 'sentences' },
  { en: 'What a shame!', it: 'Che peccato!', cat: 'sentences' },
  { en: 'Thank goodness!', it: 'Meno male!', cat: 'sentences' },
  { en: 'Come on! / No way!', it: 'Dai!', cat: 'sentences' },
  { en: 'I wish! / Maybe!', it: 'Magari!', cat: 'sentences' },
  { en: "Don't mention it!", it: 'Figurati!', cat: 'sentences' },
  { en: 'It depends.', it: 'Dipende.', cat: 'sentences' },
  { en: 'Maybe / Perhaps.', it: 'Forse.', cat: 'sentences' },
  { en: 'Of course!', it: 'Certo!', cat: 'sentences' },
  { en: 'Absolutely.', it: 'Assolutamente.', cat: 'sentences' },
  { en: "OK / That's fine.", it: 'Va bene.', cat: 'sentences' },
  { en: "It doesn't matter.", it: 'Non fa niente.', cat: 'sentences' },
  { en: 'Good luck!', it: 'In bocca al lupo!', cat: 'sentences' },
  { en: 'Thanks! (reply to good luck)', it: 'Crepi!', cat: 'sentences' },
  { en: 'Where is…?', it: 'Dove si trova…?', cat: 'sentences' },
  { en: 'How much does it cost?', it: 'Quanto costa?', cat: 'sentences' },
  { en: 'Is service included?', it: 'È incluso il servizio?', cat: 'sentences' },
  { en: 'How are you? (formal)', it: 'Come sta?', cat: 'sentences' },
  { en: 'I work as…', it: 'Lavoro come…', cat: 'sentences' },
  { en: "My Italian isn't very good.", it: 'Il mio italiano non è molto buono.', cat: 'sentences' },
]

const seen = new Set<string>()
export const ITALIANO_CARDS: ItalianoCard[] = CARDS_RAW
  .filter(c => {
    const key = `${c.it}|${c.cat}`
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
  .map(c => ({ ...c, id: `${toSlug(c.it)}-${c.cat}` }))

export const ITALIANO_CATS = [
  'All', 'greetings', 'pronouns', 'questions', 'verbs', 'nouns',
  'descriptors', 'numbers', 'colours', 'shapes', 'days', 'months',
  'body', 'time', 'particles', 'sentences',
]
