export interface MagyarCard {
  id: string
  en: string
  hu: string
  cat: string
}

function toSlug(s: string): string {
  return s
    .replace(/[áà]/g, 'a').replace(/[éè]/g, 'e').replace(/[íì]/g, 'i')
    .replace(/[óòöő]/g, 'o').replace(/[úùüű]/g, 'u')
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

const CARDS_RAW: Omit<MagyarCard, 'id'>[] = [
  // greetings
  { en: 'hello / bye', hu: 'szia', cat: 'greetings' },
  { en: 'good morning', hu: 'jó reggelt', cat: 'greetings' },
  { en: 'good evening', hu: 'jó estét', cat: 'greetings' },
  { en: 'good night', hu: 'jó éjszakát', cat: 'greetings' },
  { en: 'goodbye', hu: 'viszlát', cat: 'greetings' },
  { en: 'thank you', hu: 'köszönöm', cat: 'greetings' },
  { en: 'thank you very much', hu: 'köszönöm szépen', cat: 'greetings' },
  { en: 'please', hu: 'kérem', cat: 'greetings' },
  { en: "you're welcome", hu: 'szívesen', cat: 'greetings' },
  { en: 'excuse me (informal)', hu: 'bocsi', cat: 'greetings' },
  { en: 'excuse me (formal)', hu: 'elnézést', cat: 'greetings' },
  { en: "I'm sorry", hu: 'sajnálom', cat: 'greetings' },
  { en: 'yes', hu: 'igen', cat: 'greetings' },
  { en: 'no', hu: 'nem', cat: 'greetings' },
  { en: 'how are you? (informal)', hu: 'hogy vagy?', cat: 'greetings' },
  { en: 'fine, thanks', hu: 'jól, köszönöm', cat: 'greetings' },
  { en: "what's your name?", hu: 'mi a neved?', cat: 'greetings' },
  { en: 'my name is…', hu: 'a nevem…', cat: 'greetings' },
  { en: 'pleased to meet you', hu: 'örvendek', cat: 'greetings' },
  // pronouns
  { en: 'I', hu: 'én', cat: 'pronouns' },
  { en: 'you (singular, informal)', hu: 'te', cat: 'pronouns' },
  { en: 'you (singular, formal)', hu: 'Ön', cat: 'pronouns' },
  { en: 'he / she', hu: 'ő', cat: 'pronouns' },
  { en: 'it', hu: 'az', cat: 'pronouns' },
  { en: 'we', hu: 'mi', cat: 'pronouns' },
  { en: 'you (plural)', hu: 'ti', cat: 'pronouns' },
  { en: 'they', hu: 'ők', cat: 'pronouns' },
  // questions
  { en: 'who', hu: 'ki', cat: 'questions' },
  { en: 'what', hu: 'mi', cat: 'questions' },
  { en: 'where', hu: 'hol', cat: 'questions' },
  { en: 'when', hu: 'mikor', cat: 'questions' },
  { en: 'how', hu: 'hogyan', cat: 'questions' },
  { en: 'why / because', hu: 'miért', cat: 'questions' },
  { en: 'how much', hu: 'mennyi', cat: 'questions' },
  { en: 'how many', hu: 'hány', cat: 'questions' },
  { en: 'which', hu: 'melyik', cat: 'questions' },
  // verbs
  { en: 'to be', hu: 'lenni', cat: 'verbs' },
  { en: 'to stay / remain', hu: 'maradni', cat: 'verbs' },
  { en: 'to have / possess', hu: 'birtokolni', cat: 'verbs' },
  { en: 'to do / make', hu: 'csinálni', cat: 'verbs' },
  { en: 'to say / tell', hu: 'mondani', cat: 'verbs' },
  { en: 'to go', hu: 'menni', cat: 'verbs' },
  { en: 'to come', hu: 'jönni', cat: 'verbs' },
  { en: 'to know (a fact) / can, be able to', hu: 'tudni', cat: 'verbs' },
  { en: 'to know (a person)', hu: 'ismerni', cat: 'verbs' },
  { en: 'to want', hu: 'akarni', cat: 'verbs' },
  { en: 'to have to / must', hu: 'kell', cat: 'verbs' },
  { en: 'to give', hu: 'adni', cat: 'verbs' },
  { en: 'to see', hu: 'látni', cat: 'verbs' },
  { en: 'to hear', hu: 'hallani', cat: 'verbs' },
  { en: 'to feel', hu: 'érezni', cat: 'verbs' },
  { en: 'to speak', hu: 'beszélni', cat: 'verbs' },
  { en: 'to eat', hu: 'enni', cat: 'verbs' },
  { en: 'to drink', hu: 'inni', cat: 'verbs' },
  { en: 'to understand', hu: 'érteni', cat: 'verbs' },
  { en: 'to read', hu: 'olvasni', cat: 'verbs' },
  { en: 'to write', hu: 'írni', cat: 'verbs' },
  { en: 'to sleep', hu: 'aludni', cat: 'verbs' },
  { en: 'to work', hu: 'dolgozni', cat: 'verbs' },
  { en: 'to live (reside)', hu: 'lakni', cat: 'verbs' },
  { en: 'to take', hu: 'vinni', cat: 'verbs' },
  { en: 'to like / love', hu: 'szeretni', cat: 'verbs' },
  // nouns
  { en: 'house / home', hu: 'ház', cat: 'nouns' },
  { en: 'time / weather', hu: 'idő', cat: 'nouns' },
  { en: 'person', hu: 'ember', cat: 'nouns' },
  { en: 'man', hu: 'férfi', cat: 'nouns' },
  { en: 'woman', hu: 'nő', cat: 'nouns' },
  { en: 'child', hu: 'gyerek', cat: 'nouns' },
  { en: 'day / sun', hu: 'nap', cat: 'nouns' },
  { en: 'year', hu: 'év', cat: 'nouns' },
  { en: 'thing', hu: 'dolog', cat: 'nouns' },
  { en: 'country', hu: 'ország', cat: 'nouns' },
  { en: 'village', hu: 'falu', cat: 'nouns' },
  { en: 'city', hu: 'város', cat: 'nouns' },
  { en: 'work / job', hu: 'munka', cat: 'nouns' },
  { en: 'book', hu: 'könyv', cat: 'nouns' },
  { en: 'word', hu: 'szó', cat: 'nouns' },
  { en: 'problem', hu: 'probléma', cat: 'nouns' },
  { en: 'life', hu: 'élet', cat: 'nouns' },
  { en: 'world', hu: 'világ', cat: 'nouns' },
  { en: 'food', hu: 'étel', cat: 'nouns' },
  { en: 'water', hu: 'víz', cat: 'nouns' },
  { en: 'wine', hu: 'bor', cat: 'nouns' },
  { en: 'friend', hu: 'barát', cat: 'nouns' },
  { en: 'family', hu: 'család', cat: 'nouns' },
  { en: 'place / seat', hu: 'hely', cat: 'nouns' },
  { en: 'name', hu: 'név', cat: 'nouns' },
  { en: 'money', hu: 'pénz', cat: 'nouns' },
  // descriptors
  { en: 'big / great', hu: 'nagy', cat: 'descriptors' },
  { en: 'small', hu: 'kicsi', cat: 'descriptors' },
  { en: 'beautiful / nice', hu: 'szép', cat: 'descriptors' },
  { en: 'ugly / bad', hu: 'csúnya', cat: 'descriptors' },
  { en: 'good', hu: 'jó', cat: 'descriptors' },
  { en: 'bad / naughty', hu: 'rossz', cat: 'descriptors' },
  { en: 'new', hu: 'új', cat: 'descriptors' },
  { en: 'old (of things)', hu: 'régi', cat: 'descriptors' },
  { en: 'old (of people)', hu: 'öreg', cat: 'descriptors' },
  { en: 'long', hu: 'hosszú', cat: 'descriptors' },
  { en: 'short', hu: 'rövid', cat: 'descriptors' },
  { en: 'tall / high', hu: 'magas', cat: 'descriptors' },
  { en: 'hot / warm', hu: 'meleg', cat: 'descriptors' },
  { en: 'cold', hu: 'hideg', cat: 'descriptors' },
  { en: 'strong', hu: 'erős', cat: 'descriptors' },
  { en: 'difficult', hu: 'nehéz', cat: 'descriptors' },
  { en: 'easy', hu: 'könnyű', cat: 'descriptors' },
  { en: 'tired', hu: 'fáradt', cat: 'descriptors' },
  { en: 'happy', hu: 'boldog', cat: 'descriptors' },
  { en: 'sad', hu: 'szomorú', cat: 'descriptors' },
  { en: 'fast', hu: 'gyors', cat: 'descriptors' },
  // numbers
  { en: 'zero', hu: 'nulla', cat: 'numbers' },
  { en: 'one', hu: 'egy', cat: 'numbers' },
  { en: 'two', hu: 'kettő', cat: 'numbers' },
  { en: 'three', hu: 'három', cat: 'numbers' },
  { en: 'four', hu: 'négy', cat: 'numbers' },
  { en: 'five', hu: 'öt', cat: 'numbers' },
  { en: 'six', hu: 'hat', cat: 'numbers' },
  { en: 'seven', hu: 'hét', cat: 'numbers' },
  { en: 'eight', hu: 'nyolc', cat: 'numbers' },
  { en: 'nine', hu: 'kilenc', cat: 'numbers' },
  { en: 'ten', hu: 'tíz', cat: 'numbers' },
  { en: 'eleven', hu: 'tizenegy', cat: 'numbers' },
  { en: 'twelve', hu: 'tizenkettő', cat: 'numbers' },
  { en: 'thirteen', hu: 'tizenhárom', cat: 'numbers' },
  { en: 'fourteen', hu: 'tizennégy', cat: 'numbers' },
  { en: 'fifteen', hu: 'tizenöt', cat: 'numbers' },
  { en: 'sixteen', hu: 'tizenhat', cat: 'numbers' },
  { en: 'seventeen', hu: 'tizenhét', cat: 'numbers' },
  { en: 'eighteen', hu: 'tizennyolc', cat: 'numbers' },
  { en: 'nineteen', hu: 'tizenkilenc', cat: 'numbers' },
  { en: 'twenty', hu: 'húsz', cat: 'numbers' },
  { en: 'thirty', hu: 'harminc', cat: 'numbers' },
  { en: 'forty', hu: 'negyven', cat: 'numbers' },
  { en: 'fifty', hu: 'ötven', cat: 'numbers' },
  { en: 'one hundred', hu: 'száz', cat: 'numbers' },
  { en: 'one thousand', hu: 'ezer', cat: 'numbers' },
  // colours
  { en: 'red', hu: 'piros', cat: 'colours' },
  { en: 'blue', hu: 'kék', cat: 'colours' },
  { en: 'light blue', hu: 'világoskék', cat: 'colours' },
  { en: 'green', hu: 'zöld', cat: 'colours' },
  { en: 'yellow', hu: 'sárga', cat: 'colours' },
  { en: 'orange', hu: 'narancssárga', cat: 'colours' },
  { en: 'purple', hu: 'lila', cat: 'colours' },
  { en: 'pink', hu: 'rózsaszín', cat: 'colours' },
  { en: 'white', hu: 'fehér', cat: 'colours' },
  { en: 'black', hu: 'fekete', cat: 'colours' },
  { en: 'grey', hu: 'szürke', cat: 'colours' },
  { en: 'brown', hu: 'barna', cat: 'colours' },
  // shapes
  { en: 'circle', hu: 'kör', cat: 'shapes' },
  { en: 'square', hu: 'négyzet', cat: 'shapes' },
  { en: 'rectangle', hu: 'téglalap', cat: 'shapes' },
  { en: 'triangle', hu: 'háromszög', cat: 'shapes' },
  { en: 'oval', hu: 'ovális', cat: 'shapes' },
  { en: 'star', hu: 'csillag', cat: 'shapes' },
  { en: 'heart', hu: 'szív', cat: 'shapes' },
  // days
  { en: 'Monday', hu: 'hétfő', cat: 'days' },
  { en: 'Tuesday', hu: 'kedd', cat: 'days' },
  { en: 'Wednesday', hu: 'szerda', cat: 'days' },
  { en: 'Thursday', hu: 'csütörtök', cat: 'days' },
  { en: 'Friday', hu: 'péntek', cat: 'days' },
  { en: 'Saturday', hu: 'szombat', cat: 'days' },
  { en: 'Sunday', hu: 'vasárnap', cat: 'days' },
  // months
  { en: 'January', hu: 'január', cat: 'months' },
  { en: 'February', hu: 'február', cat: 'months' },
  { en: 'March', hu: 'március', cat: 'months' },
  { en: 'April', hu: 'április', cat: 'months' },
  { en: 'May', hu: 'május', cat: 'months' },
  { en: 'June', hu: 'június', cat: 'months' },
  { en: 'July', hu: 'július', cat: 'months' },
  { en: 'August', hu: 'augusztus', cat: 'months' },
  { en: 'September', hu: 'szeptember', cat: 'months' },
  { en: 'October', hu: 'október', cat: 'months' },
  { en: 'November', hu: 'november', cat: 'months' },
  { en: 'December', hu: 'december', cat: 'months' },
  // body
  { en: 'head', hu: 'fej', cat: 'body' },
  { en: 'face', hu: 'arc', cat: 'body' },
  { en: 'eye', hu: 'szem', cat: 'body' },
  { en: 'nose', hu: 'orr', cat: 'body' },
  { en: 'mouth', hu: 'száj', cat: 'body' },
  { en: 'ear', hu: 'fül', cat: 'body' },
  { en: 'neck', hu: 'nyak', cat: 'body' },
  { en: 'shoulder', hu: 'váll', cat: 'body' },
  { en: 'arm', hu: 'kar', cat: 'body' },
  { en: 'hand', hu: 'kéz', cat: 'body' },
  { en: 'finger', hu: 'ujj', cat: 'body' },
  { en: 'chest', hu: 'mellkas', cat: 'body' },
  { en: 'stomach', hu: 'gyomor', cat: 'body' },
  { en: 'back', hu: 'hát', cat: 'body' },
  { en: 'leg', hu: 'láb', cat: 'body' },
  { en: 'knee', hu: 'térd', cat: 'body' },
  { en: 'foot', hu: 'lábfej', cat: 'body' },
  { en: 'heart', hu: 'szív', cat: 'body' },
  // time
  { en: 'now', hu: 'most', cat: 'time' },
  { en: 'today', hu: 'ma', cat: 'time' },
  { en: 'yesterday', hu: 'tegnap', cat: 'time' },
  { en: 'tomorrow', hu: 'holnap', cat: 'time' },
  { en: 'morning', hu: 'reggel', cat: 'time' },
  { en: 'afternoon', hu: 'délután', cat: 'time' },
  { en: 'evening', hu: 'este', cat: 'time' },
  { en: 'night', hu: 'éjszaka', cat: 'time' },
  { en: 'early / soon', hu: 'korán', cat: 'time' },
  { en: 'late', hu: 'késő', cat: 'time' },
  { en: 'always', hu: 'mindig', cat: 'time' },
  { en: 'never', hu: 'soha', cat: 'time' },
  { en: 'often', hu: 'gyakran', cat: 'time' },
  { en: 'sometimes', hu: 'néha', cat: 'time' },
  { en: 'already', hu: 'már', cat: 'time' },
  { en: 'still / again', hu: 'még', cat: 'time' },
  { en: 'immediately', hu: 'azonnal', cat: 'time' },
  // particles
  { en: 'and', hu: 'és', cat: 'particles' },
  { en: 'but', hu: 'de', cat: 'particles' },
  { en: 'also / too', hu: 'is', cat: 'particles' },
  { en: 'not', hu: 'nem', cat: 'particles' },
  { en: 'very / much', hu: 'nagyon', cat: 'particles' },
  { en: 'more', hu: 'több', cat: 'particles' },
  { en: 'less', hu: 'kevesebb', cat: 'particles' },
  { en: 'here', hu: 'itt', cat: 'particles' },
  { en: 'there', hu: 'ott', cat: 'particles' },
  { en: 'between / among', hu: 'között', cat: 'particles' },
  { en: 'who (relative, people)', hu: 'aki', cat: 'particles' },
  { en: 'what / which (relative, things)', hu: 'ami', cat: 'particles' },
  { en: 'that (conjunction)', hu: 'hogy', cat: 'particles' },
  { en: 'because', hu: 'mert', cat: 'particles' },
  { en: 'in / inside (suffix)', hu: '-ban / -ben', cat: 'particles' },
  { en: 'to / towards (suffix)', hu: '-hoz / -hez / -höz', cat: 'particles' },
  { en: 'with (suffix)', hu: '-val / -vel', cat: 'particles' },
  { en: 'from (suffix)', hu: '-ból / -ből', cat: 'particles' },
  // sentences
  { en: "I don't understand.", hu: 'Nem értem.', cat: 'sentences' },
  { en: "I don't know.", hu: 'Nem tudom.', cat: 'sentences' },
  { en: 'Can you repeat?', hu: 'Meg tudod ismételni?', cat: 'sentences' },
  { en: 'Can you speak more slowly?', hu: 'Tudnál lassabban beszélni?', cat: 'sentences' },
  { en: 'How do you say… in Hungarian?', hu: 'Hogy mondják magyarul, hogy…?', cat: 'sentences' },
  { en: 'What does… mean?', hu: 'Mit jelent, hogy…?', cat: 'sentences' },
  { en: 'Do you speak English?', hu: 'Beszélsz angolul?', cat: 'sentences' },
  { en: "I'm learning Hungarian.", hu: 'Magyarul tanulok.', cat: 'sentences' },
  { en: 'I would like…', hu: 'Szeretnék…', cat: 'sentences' },
  { en: "I'm hungry.", hu: 'Éhes vagyok.', cat: 'sentences' },
  { en: "I'm thirsty.", hu: 'Szomjas vagyok.', cat: 'sentences' },
  { en: "I'm hot.", hu: 'Melegem van.', cat: 'sentences' },
  { en: "I'm cold.", hu: 'Fázom.', cat: 'sentences' },
  { en: 'I need help.', hu: 'Segítségre van szükségem.', cat: 'sentences' },
  { en: "I'm fine / I'm well.", hu: 'Jól vagyok.', cat: 'sentences' },
  { en: "I don't feel well.", hu: 'Nem érzem jól magam.', cat: 'sentences' },
  { en: 'Where is the bathroom?', hu: 'Hol van a mosdó?', cat: 'sentences' },
  { en: 'At what time…?', hu: 'Hány órakor…?', cat: 'sentences' },
  { en: 'Can I have the bill?', hu: 'Kérhetem a számlát?', cat: 'sentences' },
  { en: 'Is service included?', hu: 'A kiszolgálás benne van az árban?', cat: 'sentences' },
  { en: "I'm allergic to…", hu: 'Allergiás vagyok…', cat: 'sentences' },
  { en: "I'm vegetarian.", hu: 'Vegetáriánus vagyok.', cat: 'sentences' },
  { en: 'What time is it?', hu: 'Hány óra van?', cat: 'sentences' },
  { en: "I'm from…", hu: '…-ból/-ből származom.', cat: 'sentences' },
  { en: 'I live in…', hu: '…-ban/-ben élek.', cat: 'sentences' },
  { en: 'How old are you?', hu: 'Hány éves vagy?', cat: 'sentences' },
  { en: 'I am… years old.', hu: '…éves vagyok.', cat: 'sentences' },
  { en: 'Do you like…?', hu: 'Szereted…?', cat: 'sentences' },
  { en: 'I like it a lot.', hu: 'Nagyon szeretem.', cat: 'sentences' },
  { en: "I don't like it.", hu: 'Nem szeretem.', cat: 'sentences' },
  { en: "It's delicious!", hu: 'Nagyon finom!', cat: 'sentences' },
  { en: 'How beautiful!', hu: 'Milyen szép!', cat: 'sentences' },
  { en: 'What a shame!', hu: 'Milyen kár!', cat: 'sentences' },
  { en: 'Thank goodness!', hu: 'Hála istennek!', cat: 'sentences' },
  { en: 'Come on! / No way!', hu: 'Ugyan már!', cat: 'sentences' },
  { en: 'I wish! / Maybe!', hu: 'Bárcsak!', cat: 'sentences' },
  { en: "Don't mention it!", hu: 'Szóra sem érdemes!', cat: 'sentences' },
  { en: 'It depends.', hu: 'Attól függ.', cat: 'sentences' },
  { en: 'Maybe / Perhaps.', hu: 'Talán.', cat: 'sentences' },
  { en: 'Of course!', hu: 'Persze!', cat: 'sentences' },
  { en: "OK / That's fine.", hu: 'Rendben.', cat: 'sentences' },
  { en: "It doesn't matter.", hu: 'Nem számít.', cat: 'sentences' },
  { en: 'Good luck!', hu: 'Sok szerencsét!', cat: 'sentences' },
  { en: 'Where is…?', hu: 'Hol van…?', cat: 'sentences' },
  { en: 'How much does it cost?', hu: 'Mennyibe kerül?', cat: 'sentences' },
  { en: 'How are you? (formal)', hu: 'Hogy van?', cat: 'sentences' },
  { en: 'I work as…', hu: '…-ként dolgozom.', cat: 'sentences' },
  { en: "My Hungarian isn't very good.", hu: 'A magyar tudásom nem túl jó.', cat: 'sentences' },
]

const seen = new Set<string>()
export const MAGYAR_CARDS: MagyarCard[] = CARDS_RAW
  .filter(c => {
    const key = `${c.hu}|${c.cat}`
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
  .map(c => ({ ...c, id: `${toSlug(c.hu)}-${c.cat}` }))

export const MAGYAR_CATS = [
  'All', 'greetings', 'pronouns', 'questions', 'verbs', 'nouns',
  'descriptors', 'numbers', 'colours', 'shapes', 'days', 'months',
  'body', 'time', 'particles', 'sentences',
]
