export interface Card {
  id: string
  en: string
  tr: string
  cat: string
}

function toSlug(s: string): string {
  return s
    .replace(/ā/g, 'a').replace(/ē/g, 'e').replace(/ī/g, 'i').replace(/ō/g, 'o').replace(/ū/g, 'u')
    .replace(/Ā/g, 'a').replace(/Ē/g, 'e').replace(/Ī/g, 'i').replace(/Ō/g, 'o').replace(/Ū/g, 'u')
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

const BASE = 'https://storage.googleapis.com/maori-dictionary-prod2-web-assets/public/'

export const AUDIO: Record<string, number> = {
  'kia kaha': 11337, 'ka mutu': 2146,
  'kia ora': 2608, 'tēnā koe': 7919, 'tēnā kōrua': 7920, 'tēnā koutou': 7921, 'nau mai': 4356,
  'haere rā': 721, 'e noho rā': 660,
  'āe': 54, 'kāo': 2193,
  'au': 502, 'koe': 41987, 'ia': 1644, 'māua': 3934, 'tāua': 15321, 'rātou': 6589,
  'mātou': 3910, 'tātou': 7664, 'kōrua': 3076, 'koutou': 3165,
  'aha': 50, 'wai (who)': 9017, 'hea': 1006, 'āhea': 307, 'nōnahea': 4459, 'pēhea': 5421, 'hia': 1129,
  'kai': 1894, 'moe': 50550, 'haere': 715, 'hoki': 1352, 'noho': 4438, 'kōrero': 3003,
  'whakarongo': 9838, 'titiro': 8226, 'mahi': 14146, 'ako': 158, 'aroha': 414, 'tū': 8562,
  'oma': 15572, 'huri': 1602, 'homai': 1371, 'mōhio': 4147, 'i': 1640, 'ka': 1828,
  'kite': 2722, 'āta': 13937, 'mutu': 4294, 'ana': 206, 'anō': 239,
  'tōku': 8398, 'tōu': 8547, 'tāu': 7674, 'tāku': 7309,
  'whero': 10283, 'kōwhai': 3180, 'kākāriki': 2104, 'kikorangi': 2641, 'mā': 3481,
  'mangu': 3636, 'karaka': 2273, 'kākaka': 38979, 'māwhero': 3982, 'pāpura': 5202,
  'tapatoru': 7470, 'tapawhā': 7476, 'porohīta': 5865, 'whetu': 10293, 'porotītaha': 43998,
  'rawe': 6654, 'pō': 5689, 'atarau': 470, 'pōkarekare': 5766, 'katoa': 2399, 'rāua': 6595,
  'ao': 256, 'ata': 456, 'ahiahi': 71, 'tonu': 8429, 'kē': 2504,
  'atu': 493, 'ake': 143, 'iho': 1668, 'mai': 3474, 'engari': 661, 'ā': 39, 'nā reira': 4347,
  'tinana': 8108, 'upoko': 8896, 'kanohi': 2178, 'taringa': 7586, 'waha': 8981,
  'ringa': 6789, 'waewae': 8974, 'manawa': 3443, 'ihu': 1674,
  'māuiui': 3941, 'tau': 7680, 'kaiako': 1899, 'ākonga': 162, 'Ingarani': 13501,
  'tikanga': 8043, 'aroha mai': 10803, 'ināianei': 1713, 'āpōpō': 323, 'inanahi': 1721,
  'hiahia': 1132, 'auē': 524, 'ngākau': 53136, 'mihi': 4059, 'tino': 8122, 'āhua': 87, 'noa': 4428,
  'whare': 10111, 'kāinga': 1971, 'wāhi': 8996, 'whenua': 10256, 'moana': 52948, 'awa': 563,
  'maunga': 3952, 'ngahere': 4512, 'rangi': 6482, 'rā': 6402, 'marama': 3673, 'mārama': 3672,
  'wai': 9019, 'ahi': 69, 'tangata': 7411, 'tāne': 51482, 'wahine': 52001,
  'tamariki': 7339, 'tamaiti': 7326, 'whānau': 10062, 'iwi': 1822, 'hapū': 877,
  'ingoa': 1760, 'reo': 6700, 'waka': 9104,
  'pai': 4936, 'kino': 2663, 'nui': 4488, 'iti': 1813, 'roa': 6850, 'poto': 5925,
  'hou': 1464, 'tawhito': 7871, 'ataahua': 457, 'kaha': 1835, 'ngenge': 53183,
  'hiakai': 1134, 'hiainu': 1133, 'hari': 899, 'pōuri': 5962, 'tika': 51697, 'hē': 1004,
  'whakatoi': 9952,
  'tahi': 7059, 'rua': 6941, 'toru': 8517, 'whā': 9293, 'rima': 6777, 'ono': 4782,
  'whitu': 10356, 'waru': 9175, 'iwa': 1820, 'tekau': 7900, 'kore': 2989,
  'te': 15648, 'ngā': 53126, 'he': 1005, 'ko': 2741, 'kei': 2514, 'ki': 2596,
  'nō': 4426, 'nā': 4300, 'me': 3987, 'kāore': 2198, 'ehara': 615,
}

export function getAudioUrl(tr: string): string | null {
  if (AUDIO[tr] !== undefined) return `${BASE}${AUDIO[tr]}.mp3`
  const clean = tr.toLowerCase().replace(/[^a-zāēīōū\s]/g, '').trim()
  if (AUDIO[clean] !== undefined) return `${BASE}${AUDIO[clean]}.mp3`
  return null
}

const CARDS_RAW = [
  { en: 'hello / thank you', tr: 'kia ora', cat: 'greetings' },
  { en: 'greetings (to one person)', tr: 'tēnā koe', cat: 'greetings' },
  { en: 'greetings (to two people)', tr: 'tēnā kōrua', cat: 'greetings' },
  { en: 'greetings (to three or more)', tr: 'tēnā koutou', cat: 'greetings' },
  { en: 'welcome', tr: 'nau mai', cat: 'greetings' },
  { en: 'goodbye (to someone leaving)', tr: 'haere rā', cat: 'greetings' },
  { en: 'goodbye (said by the one leaving)', tr: 'e noho rā', cat: 'greetings' },
  { en: 'yes', tr: 'āe', cat: 'basics' },
  { en: 'no', tr: 'kāo', cat: 'basics' },
  { en: 'I / me', tr: 'au', cat: 'pronouns' },
  { en: 'you (one person)', tr: 'koe', cat: 'pronouns' },
  { en: 'he / she / they (one)', tr: 'ia', cat: 'pronouns' },
  { en: 'we two (not you)', tr: 'māua', cat: 'pronouns' },
  { en: 'we two (including you)', tr: 'tāua', cat: 'pronouns' },
  { en: 'they (three or more)', tr: 'rātou', cat: 'pronouns' },
  { en: 'they two', tr: 'rāua', cat: 'pronouns' },
  { en: 'we (three+, not you)', tr: 'mātou', cat: 'pronouns' },
  { en: 'we all (three+, including you)', tr: 'tātou', cat: 'pronouns' },
  { en: 'you two', tr: 'kōrua', cat: 'pronouns' },
  { en: 'you all (three+)', tr: 'koutou', cat: 'pronouns' },
  { en: 'what', tr: 'aha', cat: 'questions' },
  { en: 'who', tr: 'wai', cat: 'questions' },
  { en: 'where', tr: 'hea', cat: 'questions' },
  { en: 'when (future)', tr: 'āhea', cat: 'questions' },
  { en: 'when (past)', tr: 'nōnahea', cat: 'questions' },
  { en: 'how / what like', tr: 'pēhea', cat: 'questions' },
  { en: 'how many', tr: 'hia', cat: 'questions' },
  { en: 'eat / food', tr: 'kai', cat: 'verbs' },
  { en: 'sleep', tr: 'moe', cat: 'verbs' },
  { en: 'go / travel', tr: 'haere', cat: 'verbs' },
  { en: 'return / also', tr: 'hoki', cat: 'verbs' },
  { en: 'sit / stay / live', tr: 'noho', cat: 'verbs' },
  { en: 'speak / talk', tr: 'kōrero', cat: 'verbs' },
  { en: 'listen', tr: 'whakarongo', cat: 'verbs' },
  { en: 'look', tr: 'titiro', cat: 'verbs' },
  { en: 'work / do', tr: 'mahi', cat: 'verbs' },
  { en: 'learn / teach', tr: 'ako', cat: 'verbs' },
  { en: 'love / care', tr: 'aroha', cat: 'verbs' },
  { en: 'stand', tr: 'tū', cat: 'verbs' },
  { en: 'run', tr: 'oma', cat: 'verbs' },
  { en: 'turn', tr: 'huri', cat: 'verbs' },
  { en: 'give (to me)', tr: 'homai', cat: 'verbs' },
  { en: 'know / understand', tr: 'mōhio', cat: 'verbs' },
  { en: 'see / find', tr: 'kite', cat: 'verbs' },
  { en: 'past tense marker', tr: 'i', cat: 'particles' },
  { en: 'narrative / sequential tense marker', tr: 'ka', cat: 'particles' },
  { en: 'ongoing action suffix', tr: 'ana', cat: 'particles' },
  { en: 'again / still / also', tr: 'anō', cat: 'particles' },
  { en: 'gently / carefully', tr: 'āta', cat: 'particles' },
  { en: 'understand / clear / bright', tr: 'mārama', cat: 'verbs' },
  { en: 'unwell / sick', tr: 'māuiui', cat: 'descriptors' },
  { en: 'year / to settle / count', tr: 'tau', cat: 'nouns' },
  { en: 'teacher', tr: 'kaiako', cat: 'nouns' },
  { en: 'student / learner', tr: 'ākonga', cat: 'nouns' },
  { en: 'England', tr: 'Ingarani', cat: 'nouns' },
  { en: 'custom / meaning / protocol', tr: 'tikanga', cat: 'nouns' },
  { en: 'want / desire', tr: 'hiahia', cat: 'verbs' },
  { en: 'now / at this moment', tr: 'ināianei', cat: 'particles' },
  { en: 'tomorrow', tr: 'āpōpō', cat: 'particles' },
  { en: 'yesterday', tr: 'inanahi', cat: 'particles' },
  { en: 'alas! / oh no!', tr: 'auē', cat: 'basics' },
  { en: 'heart / innermost feelings', tr: 'ngākau', cat: 'nouns' },
  { en: 'greet / acknowledge / tribute', tr: 'mihi', cat: 'verbs' },
  { en: 'very / extremely', tr: 'tino', cat: 'particles' },
  { en: 'appearance / somewhat / about', tr: 'āhua', cat: 'particles' },
  { en: 'just / only / freely / without reason', tr: 'noa', cat: 'particles' },
  { en: 'sorry / excuse me / forgive me', tr: 'aroha mai', cat: 'sentences' },
  { en: 'how are you?', tr: 'kei te pēhea koe?', cat: 'sentences' },
  { en: "I'm very well", tr: 'kei te pai rawa atu au', cat: 'sentences' },
  { en: "I'm pretty good", tr: 'kei te āhua pai au', cat: 'sentences' },
  { en: "I'm unwell / sick", tr: 'kei te māuiui au', cat: 'sentences' },
  { en: 'how old are you?', tr: 'e hia ō tau?', cat: 'sentences' },
  { en: 'I am ___ years old', tr: 'e ___ ōku tau', cat: 'sentences' },
  { en: 'what is your job?', tr: 'he aha tō mahi?', cat: 'sentences' },
  { en: 'I am a teacher', tr: 'he kaiako au', cat: 'sentences' },
  { en: 'I am a student', tr: 'he ākonga au', cat: 'sentences' },
  { en: 'I am from England', tr: 'nō Ingarani au', cat: 'sentences' },
  { en: 'I live in ___', tr: 'e noho ana au i ___', cat: 'sentences' },
  { en: "I don't understand", tr: 'kāore au i te mārama', cat: 'sentences' },
  { en: 'do you understand?', tr: 'kei te mārama koe?', cat: 'sentences' },
  { en: 'please say that again', tr: 'tēnā, kōrero anō', cat: 'sentences' },
  { en: 'speak slowly please', tr: 'āta kōrero mai', cat: 'sentences' },
  { en: 'what does ___ mean?', tr: 'he aha te tikanga o ___?', cat: 'sentences' },
  { en: 'I am learning te reo Māori', tr: 'kei te ako au i te reo Māori', cat: 'sentences' },
  { en: 'no worries / it\'s nothing', tr: 'kāore he aha', cat: 'sentences' },
  { en: 'excellent! / very good!', tr: 'tino pai!', cat: 'sentences' },
  { en: "let's eat", tr: 'me kai tātou', cat: 'sentences' },
  { en: 'what do you want?', tr: 'he aha tāu e hiahia ana?', cat: 'sentences' },
  { en: 'give me that', tr: 'homai tēnā', cat: 'sentences' },
  { en: "I don't want it", tr: 'kāore au e hiahia ana', cat: 'sentences' },
  { en: 'today', tr: 'i tēnei rā', cat: 'sentences' },
  { en: 'where is ___?', tr: 'kei hea ___?', cat: 'sentences' },
  { en: 'my heart is very happy', tr: 'ka nui te hari o tōku ngākau', cat: 'sentences' },
  { en: 'my regards / much love', tr: 'he nui ake ōku mihi', cat: 'sentences' },
  { en: 'finished / ended', tr: 'mutu', cat: 'particles' },
  { en: 'my (ō class — people, places, feelings)', tr: 'tōku', cat: 'possessives' },
  { en: 'your (ō class — one person)', tr: 'tōu', cat: 'possessives' },
  { en: 'my (ā class — actions, objects)', tr: 'tāku', cat: 'possessives' },
  { en: 'your (ā class — one person)', tr: 'tāu', cat: 'possessives' },
  { en: 'red', tr: 'whero', cat: 'colours' },
  { en: 'yellow', tr: 'kōwhai', cat: 'colours' },
  { en: 'green', tr: 'kākāriki', cat: 'colours' },
  { en: 'blue', tr: 'kikorangi', cat: 'colours' },
  { en: 'white', tr: 'mā', cat: 'colours' },
  { en: 'black', tr: 'mangu', cat: 'colours' },
  { en: 'orange', tr: 'karaka', cat: 'colours' },
  { en: 'brown', tr: 'kākaka', cat: 'colours' },
  { en: 'pink', tr: 'māwhero', cat: 'colours' },
  { en: 'purple', tr: 'pāpura', cat: 'colours' },
  { en: 'awesome / excellent / fantastic', tr: 'rawe', cat: 'descriptors' },
  { en: 'night', tr: 'pō', cat: 'nouns' },
  { en: 'moonlit / reflected moonlight', tr: 'atarau', cat: 'nouns' },
  { en: 'rippling / agitated (as water)', tr: 'pōkarekare', cat: 'descriptors' },
  { en: 'all / everyone / everything', tr: 'katoa', cat: 'particles' },
  { en: 'daytime / world / dawn', tr: 'ao', cat: 'nouns' },
  { en: 'morning / dawn', tr: 'ata', cat: 'nouns' },
  { en: 'afternoon / evening', tr: 'ahiahi', cat: 'nouns' },
  { en: 'still / always / continuously', tr: 'tonu', cat: 'particles' },
  { en: 'already / different / instead', tr: 'kē', cat: 'particles' },
  { en: 'away from speaker', tr: 'atu', cat: 'particles' },
  { en: 'upward', tr: 'ake', cat: 'particles' },
  { en: 'downward', tr: 'iho', cat: 'particles' },
  { en: 'towards speaker', tr: 'mai', cat: 'particles' },
  { en: 'but / however', tr: 'engari', cat: 'particles' },
  { en: 'and then / and so', tr: 'ā', cat: 'particles' },
  { en: 'therefore / so / that\'s why', tr: 'nā reira', cat: 'particles' },
  { en: 'body', tr: 'tinana', cat: 'body' },
  { en: 'head', tr: 'upoko', cat: 'body' },
  { en: 'face / eye', tr: 'kanohi', cat: 'body' },
  { en: 'ear', tr: 'taringa', cat: 'body' },
  { en: 'mouth', tr: 'waha', cat: 'body' },
  { en: 'hand / arm', tr: 'ringa', cat: 'body' },
  { en: 'foot / leg', tr: 'waewae', cat: 'body' },
  { en: 'breath / heart / lungs', tr: 'manawa', cat: 'body' },
  { en: 'nose', tr: 'ihu', cat: 'body' },
  { en: 'triangle', tr: 'tapatoru', cat: 'shapes' },
  { en: 'square / rectangle', tr: 'tapawhā', cat: 'shapes' },
  { en: 'circle', tr: 'porohīta', cat: 'shapes' },
  { en: 'star', tr: 'whetu', cat: 'shapes' },
  { en: 'oval / ellipse', tr: 'porotītaha', cat: 'shapes' },
  { en: 'house / building', tr: 'whare', cat: 'nouns' },
  { en: 'home / village', tr: 'kāinga', cat: 'nouns' },
  { en: 'place', tr: 'wāhi', cat: 'nouns' },
  { en: 'land', tr: 'whenua', cat: 'nouns' },
  { en: 'sea / ocean', tr: 'moana', cat: 'nouns' },
  { en: 'river', tr: 'awa', cat: 'nouns' },
  { en: 'mountain', tr: 'maunga', cat: 'nouns' },
  { en: 'forest', tr: 'ngahere', cat: 'nouns' },
  { en: 'sky / day', tr: 'rangi', cat: 'nouns' },
  { en: 'sun / day / sail', tr: 'rā', cat: 'nouns' },
  { en: 'moon / month', tr: 'marama', cat: 'nouns' },
  { en: 'water', tr: 'wai', cat: 'nouns' },
  { en: 'fire', tr: 'ahi', cat: 'nouns' },
  { en: 'person', tr: 'tangata', cat: 'nouns' },
  { en: 'man', tr: 'tāne', cat: 'nouns' },
  { en: 'woman', tr: 'wahine', cat: 'nouns' },
  { en: 'children', tr: 'tamariki', cat: 'nouns' },
  { en: 'child', tr: 'tamaiti', cat: 'nouns' },
  { en: 'family', tr: 'whānau', cat: 'nouns' },
  { en: 'tribe / people', tr: 'iwi', cat: 'nouns' },
  { en: 'subtribe', tr: 'hapū', cat: 'nouns' },
  { en: 'name', tr: 'ingoa', cat: 'nouns' },
  { en: 'language / voice', tr: 'reo', cat: 'nouns' },
  { en: 'canoe / vehicle', tr: 'waka', cat: 'nouns' },
  { en: 'good', tr: 'pai', cat: 'descriptors' },
  { en: 'bad', tr: 'kino', cat: 'descriptors' },
  { en: 'big / many', tr: 'nui', cat: 'descriptors' },
  { en: 'small', tr: 'iti', cat: 'descriptors' },
  { en: 'long / tall', tr: 'roa', cat: 'descriptors' },
  { en: 'short', tr: 'poto', cat: 'descriptors' },
  { en: 'new', tr: 'hou', cat: 'descriptors' },
  { en: 'old', tr: 'tawhito', cat: 'descriptors' },
  { en: 'beautiful', tr: 'ataahua', cat: 'descriptors' },
  { en: 'strong', tr: 'kaha', cat: 'descriptors' },
  { en: 'tired', tr: 'ngenge', cat: 'descriptors' },
  { en: 'hungry', tr: 'hiakai', cat: 'descriptors' },
  { en: 'thirsty', tr: 'hiainu', cat: 'descriptors' },
  { en: 'happy', tr: 'hari', cat: 'descriptors' },
  { en: 'sad', tr: 'pōuri', cat: 'descriptors' },
  { en: 'correct / right', tr: 'tika', cat: 'descriptors' },
  { en: 'wrong', tr: 'hē', cat: 'descriptors' },
  { en: 'cheeky / playfully mischievous', tr: 'whakatoi', cat: 'descriptors' },
  { en: 'one', tr: 'tahi', cat: 'numbers' },
  { en: 'two', tr: 'rua', cat: 'numbers' },
  { en: 'three', tr: 'toru', cat: 'numbers' },
  { en: 'four', tr: 'whā', cat: 'numbers' },
  { en: 'five', tr: 'rima', cat: 'numbers' },
  { en: 'six', tr: 'ono', cat: 'numbers' },
  { en: 'seven', tr: 'whitu', cat: 'numbers' },
  { en: 'eight', tr: 'waru', cat: 'numbers' },
  { en: 'nine', tr: 'iwa', cat: 'numbers' },
  { en: 'ten', tr: 'tekau', cat: 'numbers' },
  { en: 'zero / void / nothingness', tr: 'kore', cat: 'numbers' },
  { en: 'the (singular)', tr: 'te', cat: 'particles' },
  { en: 'the (plural)', tr: 'ngā', cat: 'particles' },
  { en: 'a / an / some', tr: 'he', cat: 'particles' },
  { en: 'is / identifies', tr: 'ko', cat: 'particles' },
  { en: 'at (present location)', tr: 'kei', cat: 'particles' },
  { en: 'to / towards', tr: 'ki', cat: 'particles' },
  { en: 'from / origin (past)', tr: 'nō', cat: 'particles' },
  { en: 'by / belonging to (recent)', tr: 'nā', cat: 'particles' },
  { en: 'and / with', tr: 'me', cat: 'particles' },
  { en: 'no / not', tr: 'kāore', cat: 'particles' },
  { en: 'is not', tr: 'ehara', cat: 'particles' },
  { en: 'present action: I am eating', tr: 'kei te kai au', cat: 'sentences' },
  { en: 'past action: I went', tr: 'i haere au', cat: 'sentences' },
  { en: 'narrative tense: she went', tr: 'ka haere ia', cat: 'sentences' },
  { en: 'should: we two should go', tr: 'me haere tāua', cat: 'sentences' },
  { en: 'my name is...', tr: 'ko ___ tōku ingoa', cat: 'sentences' },
  { en: 'what is your name?', tr: 'ko wai tōu ingoa?', cat: 'sentences' },
  { en: 'where are you from?', tr: 'nō hea koe?', cat: 'sentences' },
  { en: 'I am from...', tr: 'nō ___ au', cat: 'sentences' },
  { en: "I don't know", tr: 'kāore au e mōhio ana', cat: 'sentences' },
  { en: 'he / she is a good person', tr: 'he tangata pai ia', cat: 'sentences' },
  { en: 'listen here!', tr: 'whakarongo mai!', cat: 'sentences' },
  { en: 'be strong / keep going', tr: 'kia kaha', cat: 'sentences' },
  { en: 'take it easy / go gently', tr: 'āta haere', cat: 'sentences' },
  { en: 'see you', tr: 'ka kite', cat: 'sentences' },
  { en: 'see you again', tr: 'ka kite anō', cat: 'sentences' },
  { en: "it's good / that's fine", tr: 'kei te pai', cat: 'sentences' },
  { en: "I'm tired", tr: 'kei te ngenge au', cat: 'sentences' },
  { en: "I'm hungry", tr: 'kei te hiakai au', cat: 'sentences' },
  { en: 'what are you doing?', tr: 'he aha tāu mahi?', cat: 'sentences' },
  { en: 'I am going to the house', tr: 'kei te haere au ki te whare', cat: 'sentences' },
  { en: 'thank you very much', tr: 'kia ora rawa atu', cat: 'sentences' },
  { en: "it's finished / that's it", tr: 'ka mutu', cat: 'sentences' },
]

const seen = new Set<string>()
export const ALL_CARDS: Card[] = CARDS_RAW
  .filter(c => {
    const key = `${c.tr}|${c.cat}`
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
  .map(c => ({ ...c, id: `${toSlug(c.tr)}-${c.cat}` }))

export const DECKS: Record<string, Card[]> = {
  all: ALL_CARDS,
  vocab: ALL_CARDS.filter(c => ['nouns', 'verbs', 'descriptors'].includes(c.cat)),
  sentences: ALL_CARDS.filter(c => c.cat === 'sentences'),
  possessives: ALL_CARDS.filter(c => c.cat === 'possessives'),
  colours: ALL_CARDS.filter(c => c.cat === 'colours'),
  shapes: ALL_CARDS.filter(c => c.cat === 'shapes'),
  body: ALL_CARDS.filter(c => c.cat === 'body'),
  particles: ALL_CARDS.filter(c => c.cat === 'particles'),
  pronouns: ALL_CARDS.filter(c => c.cat === 'pronouns'),
  numbers: ALL_CARDS.filter(c => c.cat === 'numbers'),
}
