export interface Card {
  id: string
  en: string
  tr: string
  cat: string
}

function toSlug(s: string): string {
  return s
    .replace(/ā/g, 'a').replace(/ē/g, 'e').replace(/ī/g, 'i').replace(/ō/g, 'o').replace(/ū/g, 'u')
    .replace(/Ā/g, 'a').replace(/Ē/g, 'e').replace(/Ī/g, 'i').replace(/Ō/g, 'o').replace(/Ū/g, 'u')
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

const BASE = 'https://storage.googleapis.com/maori-dictionary-prod2-web-assets/public/'

export const AUDIO: Record<string, number> = {
  'kia kaha': 11337, 'ka mutu': 2146,
  'kia ora': 2608, 'tēnā koe': 7919, 'tēnā kōrua': 7920, 'tēnā koutou': 7921, 'nau mai': 4356,
  'haere rā': 721, 'e noho rā': 660,
  'āe': 54, 'kāo': 2193,
  'au': 502, 'koe': 41987, 'ia': 1644, 'māua': 3934, 'tāua': 15321, 'rātou': 6589,
  'mātou': 3910, 'tātou': 7664, 'kōrua': 3076, 'koutou': 3165,
  'aha': 50, 'wai (who)': 9017, 'hea': 1006, 'āhea': 307, 'nōnahea': 4459, 'pēhea': 5421, 'hia': 1129,
  'kai': 1894, 'moe': 50550, 'haere': 715, 'hoki': 1352, 'noho': 4438, 'kōrero': 3003,
  'whakarongo': 9838, 'titiro': 8226, 'mahi': 14146, 'ako': 158, 'aroha': 414, 'tū': 8562,
  'oma': 15572, 'huri': 1602, 'homai': 1371, 'mōhio': 4147, 'i': 1640, 'ka': 1828,
  'kite': 2722, 'āta': 13937, 'mutu': 4294, 'ana': 206, 'anō': 239,
  'tōku': 8398, 'tōu': 8547, 'tāu': 7674, 'tāku': 7309,
  'whero': 10283, 'kōwhai': 3180, 'kākāriki': 2104, 'kikorangi': 2641, 'mā': 3481,
  'mangu': 3636, 'karaka': 2273, 'kākaka': 38979, 'māwhero': 3982, 'pāpura': 5202,
  'tapatoru': 7470, 'tapawhā': 7476, 'porohīta': 5865, 'whetu': 10293, 'porotītaha': 43998,
  'rawe': 6654, 'pō': 5689, 'atarau': 470, 'pōkarekare': 5766, 'katoa': 2399, 'rāua': 6595,
  'ao': 256, 'ata': 456, 'ahiahi': 71, 'tonu': 8429, 'kē': 2504,
  'atu': 493, 'ake': 143, 'iho': 1668, 'mai': 3474, 'engari': 661, 'ā': 39, 'nā reira': 4347,
  'tinana': 8108, 'upoko': 8896, 'kanohi': 2178, 'taringa': 7586, 'waha': 8981,
  'ringa': 6789, 'waewae': 8974, 'manawa': 3443, 'ihu': 1674,
  'māuiui': 3941, 'tau': 7680, 'kaiako': 1899, 'ākonga': 162, 'Ingarani': 13501,
  'tikanga': 8043, 'aroha mai': 10803, 'ināianei': 1713, 'āpōpō': 323, 'inanahi': 1721,
  'hiahia': 1132, 'auē': 524, 'ngākau': 53136, 'mihi': 4059, 'tino': 8122, 'āhua': 87, 'noa': 4428,
  'whare': 10111, 'kāinga': 1971, 'wāhi': 8996, 'whenua': 10256, 'moana': 52948, 'awa': 563,
  'maunga': 3952, 'ngahere': 4512, 'rangi': 6482, 'rā': 6402, 'marama': 3673, 'mārama': 3672,
  'wai': 9019, 'ahi': 69, 'tangata': 7411, 'tāne': 51482, 'wahine': 52001,
  'tamariki': 7339, 'tamaiti': 7326, 'whānau': 10062, 'iwi': 1822, 'hapū': 877,
  'ingoa': 1760, 'reo': 6700, 'waka': 9104,
  'pai': 4936, 'kino': 2663, 'nui': 4488, 'iti': 1813, 'roa': 6850, 'poto': 5925,
  'hou': 1464, 'tawhito': 7871, 'ataahua': 457, 'kaha': 1835, 'ngenge': 53183,
  'hiakai': 1134, 'hiainu': 1133, 'hari': 899, 'pōuri': 5962, 'tika': 51697, 'hē': 1004,
  'whakatoi': 9952,
  'tahi': 7059, 'rua': 6941, 'toru': 8517, 'whā': 9293, 'rima': 6777, 'ono': 4782,
  'whitu': 10356, 'waru': 9175, 'iwa': 1820, 'tekau': 7900, 'kore': 2989,
  'te': 15648, 'ngā': 53126, 'he': 1005, 'ko': 2741, 'kei': 2514, 'ki': 2596,
  'nō': 4426, 'nā': 4300, 'me': 3987, 'kāore': 2198, 'ehara': 615,
  // Animals
  'kurī': 3309, 'ngeru': 4658, 'poaka': 5694, 'hipi': 1228, 'kau': 2408,
  'hōiho': 1336, 'heihei': 1030, 'manu': 3465, 'ika': 1684, 'tūī': 8660,
  'kea': 2505, 'kererū': 2574, 'rāpeti': 6518, 'pūngāwerewere': 6212, 'kiore': 2671,
  // Food
  'kūmara': 3249, 'rīwai': 6843, 'āporo': 324, 'parāoa': 5251, 'miraka': 4091,
  'huka': 1547, 'kawhe': 2501, 'tī': 7986, 'mīti': 4111, 'hēki': 1053,
  'tote': 8525, 'hua rākau': 48542, 'huawhenua': 1512,
  // Family
  'pāpā': 5112, 'whaea': 9297, 'tuakana': 8581, 'teina': 7892, 'tuahine': 8570,
  'tungāne': 8722, 'koroua': 3065, 'kuia': 3220, 'mokopuna': 4178, 'hoa': 1288,
  'tama': 7321, 'tamāhine': 7323,
  // Weather / nature
  'ua': 8848, 'hau': 924, 'kapua': 2250, 'marangai': 3691,
  // Days of the week
  'Rāhina': 6412, 'Rātū': 6590, 'Rāapa': 6407, 'Rāpare': 6516, 'Rāmere': 6461,
  'Rāhoroi': 6419, 'Rātapu': 6580,
  // Verbs
  'tuhi': 8645, 'pānui': 5085, 'inu': 1754, 'tangi': 7423, 'kata': 2370,
  'oho': 4708, 'pātai': 5343, 'whakautu': 9997, 'tiki': 8062, 'hopu': 1405,
  'tunu': 8712, 'horoi': 1438, 'hoko': 1362, 'whakaaro': 9369,
  // Descriptors
  'wera': 9229, 'makariri': 3393, 'mākūkū': 3556, 'maroke': 3737, 'riri': 6821,
  'whakamā': 9554, 'ora': 4791, 'ngāwari': 4641, 'uaua': 8854,
  // Everyday objects / places
  'pukapuka': 6095, 'tūru': 8790, 'tēpu': 7941, 'whāriki': 10182, 'waea': 8955,
  'waea pūkoro': 8957, 'rorohiko': 6926, 'kura': 3288, 'hōhipera': 1319, 'moni': 4198,
  // Time
  'wiki': 9261, 'hāora': 854, 'meneti': 4022,
  // Demonstratives
  'tēnei': 7927, 'tērā': 7944, 'kāti': 2386,
  // Numbers 11-19
  'tekau mā tahi': 11759, 'tekau mā rua': 11761, 'tekau mā toru': 11763,
  'tekau mā whā': 11765, 'tekau mā rima': 11767, 'tekau mā ono': 11769,
  'tekau mā whitu': 11771, 'tekau mā waru': 11773, 'tekau mā iwa': 11775,
  // ---- Added: te reo tongues expansion audio (2026-09) ----
  'mōrena': 4212,
  'haere mai': 717,
  'hongi': 1387,
  'harirū': 907,
  'pea': 5415,
  'koia': 2820,
  'ka pai': 13473,
  'tēhea': 7887,
  'he aha ai': 40548,
  'mātakitaki': 3773,
  'tākaro': 7236,
  'wānanga': 9145,
  'tirotiro': 8207,
  'whakamahi': 9562,
  'tango': 7430,
  'whiwhi': 10361,
  'tautoko': 7796,
  'āwhina': 597,
  'whakatau': 9898,
  'karanga': 2286,
  'whakapono': 9758,
  'mahara': 3345,
  'wareware': 9170,
  'maumahara': 3946,
  'tiaki': 7995,
  'whāngai': 10085,
  'kuhu': 3217,
  'puta': 6330,
  'tahuri': 7085,
  'whakamātau': 9613,
  'rapu': 6523,
  'kimi': 2644,
  'whakaatu': 9379,
  'whakamārama': 9594,
  'tīmata': 8092,
  'whakaoti': 9706,
  'whakatipu': 9941,
  'kaukau': 2431,
  'kanikani': 2171,
  'waiata': 9026,
  'tono': 8426,
  'whakawhiti': 10037,
  'kukume': 3242,
  'pana': 5064,
  'piki': 5582,
  'rere': 6719,
  'hinga': 1218,
  'pakaru': 4982,
  'tuku': 8677,
  'tāpiri': 7491,
  'whakatika': 9935,
  'tatari': 7648,
  'tūtaki': 8808,
  'kua': 3198,
  'nei': 4374,
  'ai': 111,
  'mō': 4117,
  'rānei': 6466,
  'ahakoa': 56,
  'anake': 213,
  'roto': 6934,
  'tētahi': 7968,
  'arā': 331,
  'taua': 7687,
  'mea': 3988,
  'hei': 1018,
  'konei': 2912,
  'tēnā': 7913,
  'ērā': 683,
  'hōhā': 1316,
  'pukuriri': 6159,
  'māharahara': 3493,
  'koa': 2745,
  'mataku': 3777,
  'teitei': 7895,
  'rerekē': 6725,
  'tapu': 7504,
  'wātea': 9181,
  'kahurangi': 1885,
  'waimarie': 9054,
  'rongonui': 6896,
  'ngaro': 4579,
  'tūpato': 8743,
  'maha': 3343,
  'nunui': 4501,
  'tuwhera': 8845,
  'kī': 2593,
  'ngū': 4682,
  'haruru': 911,
  'pakeke': 5001,
  'rahi': 6411,
  'tere': 7953,
  'māmā': 3561,
  'haumaru': 12747,
  'kupu': 3275,
  'kaupapa': 2439,
  'taonga': 7418,
  'mātua': 3912,
  'rangatira': 6479,
  'kaumātua': 10799,
  'tohunga': 8316,
  'atua': 494,
  'wairua': 9082,
  'mana': 3424,
  'marae': 3664,
  'hui': 1528,
  'haka': 751,
  'whakapapa': 9727,
  'rohe': 6855,
  'kaitiaki': 2015,
  'koha': 2771,
  'hākari': 755,
  'kaimahi': 1956,
  'pēpi': 5498,
  'hoariri': 1305,
  'taumata': 7723,
  'tūranga': 8762,
  'kitenga': 38787,
  'hokinga': 1360,
  'take': 7261,
  'raruraru': 6571,
  'wā': 8952,
  'whakaaturanga': 9382,
  'whakaahua': 9347,
  'pikitia': 5592,
  'tauira': 7706,
  'oranga': 4793,
  'hauora': 958,
  'mamae': 3417,
  'hā': 704,
  'kākahu': 2087,
  'pōtae': 5898,
  'hū': 1478,
  'tarau': 7560,
  'koti': 3127,
  'paraikete': 5220,
  'huarahi': 1501,
  'tāone': 7417,
  'kōhatu': 2779,
  'puke': 6120,
  'one': 4762,
  'motu': 4241,
  'tai': 7091,
  'ngaru': 4584,
  'ngutu': 4686,
  'niho': 4400,
  'makawe': 3476,
  'karu': 2360,
  'roimata': 6868,
  'kapu': 2249,
  'pereti': 5519,
  'kāpata': 2223,
  'moenga': 4132,
  'pepa': 13086,
  'whārangi': 10104,
  'kete': 2580,
  'mahere': 3350,
  'karani': 14043,
  'huia': 1529,
  'tohu': 8304,
  'wehi': 9208,
  'ture': 8768,
  'kaipuke': 1987,
  'taraka': 7531,
  'motokā': 4235,
  'tereina': 7957,
  'waka rererangi': 9121,
  'kiwi': 2734,
  'toroa': 8478,
  'pī': 5542,
  'poi': 5730,
  'pounamu': 5954,
  'hinu': 1210,
  'ate': 477,
  'puku': 6145,
  'uma': 8882,
  'harikoa': 904,
  'pouaka': 5932,
  'pouaka whakaata': 5938,
  'reo irirangi': 6705,
  'reta': 6735,
  'wharepaku': 11568,
  'haerenga': 718,
  'ngahuru': 4517,
  'raumati': 6611,
  'hōtoke': 1460,
  'kōanga': 2748,
  'kiwikiwi': 2736,
  'kōura': 3157,
  'hiriwa': 1256,
  'kōpū': 2962,
  'kiri': 2679,
  'toto': 8533,
  'kakī': 2114,
  'pokohiwi': 5788,
  'matimati': 3897,
  'turi': 8778,
  'poutū': 38953,
  'whakapae': 9708,
  'tuatahi': 13402,
  'tuarua': 8611,
  'tuatoru': 8620,
  'tuawhā': 44960,
  'tuarima': 44961,
  'tini': 8115,
  'tokorua': 8392,
  'Kohitātea': 2802,
  'Huitanguru': 1540,
  'Poutūterangi': 5980,
  'Paengawhāwhā': 4872,
  'Haratua': 893,
  'Pipiri': 5632,
  'Hōngongoi': 1393,
  'Mahuru': 3473,
  'Whiringa-ā-nuku': 10328,
  'Whiringa-ā-rangi': 10329,
  'Hakihea': 770,
  'pōwhiri': 5989,
  'mihi whakatau': 11550,
  'karakia': 2275,
  'mauri': 3960,
  'manaakitanga': 3426,
  'kotahitanga': 3094,
  'whanaungatanga': 10068,
  'wharenui': 10137,
  'wharekai': 10120,
  'paepae': 4874,
  'kaikōrero': 1949,
  'manuhiri': 3467,
  'tangata whenua': 7420,
  'ahurea': 101,
  'whakaute': 11092,
  'mahi tahi': 46391,
  'tangihanga': 7424,
  'whaikōrero': 9313,
  'waiata tangi': 9031,
  'patu': 5384,
  'tekoteko': 7908,
  'whakairo': 9480,
  'tā moko': 39261,
  'kaitiakitanga': 2018,
  'rangatiratanga': 6480,
  'tino rangatiratanga': 8124,
  'utu': 8937,
  'ihi': 1661,
  'whakanui': 9673,
  'whakahoki': 9452,
  'pakihi': 5016,
  'pūtea': 6358,
  'rawa': 6644,
  'toa': 8278,
  'angitu': 253,
  'ngoikore': 4669,
  'pakari': 4980,
  'pērā': 5500,
  'i muri': 1698,
  'i mua': 1694,
  'anā': 205,
  'pūhoi': 6070,
  'pēnei': 5466,
  'hōtēra': 1458,
}

export function getAudioUrl(tr: string): string | null {
  if (AUDIO[tr] !== undefined) return `${BASE}${AUDIO[tr]}.mp3`
  const clean = tr.toLowerCase().replace(/[^a-zāēīōū\s]/g, '').trim()
  if (AUDIO[clean] !== undefined) return `${BASE}${AUDIO[clean]}.mp3`
  return null
}

const CARDS_RAW = [
  { en: 'hello / thank you', tr: 'kia ora', cat: 'greetings' },
  { en: 'greetings (to one person)', tr: 'tēnā koe', cat: 'greetings' },
  { en: 'greetings (to two people)', tr: 'tēnā kōrua', cat: 'greetings' },
  { en: 'greetings (to three or more)', tr: 'tēnā koutou', cat: 'greetings' },
  { en: 'welcome', tr: 'nau mai', cat: 'greetings' },
  { en: 'goodbye (to someone leaving)', tr: 'haere rā', cat: 'greetings' },
  { en: 'goodbye (said by the one leaving)', tr: 'e noho rā', cat: 'greetings' },
  { en: 'yes', tr: 'āe', cat: 'basics' },
  { en: 'no', tr: 'kāo', cat: 'basics' },
  { en: 'I / me', tr: 'au', cat: 'pronouns' },
  { en: 'you (one person)', tr: 'koe', cat: 'pronouns' },
  { en: 'he / she / they (one)', tr: 'ia', cat: 'pronouns' },
  { en: 'we two (not you)', tr: 'māua', cat: 'pronouns' },
  { en: 'we two (including you)', tr: 'tāua', cat: 'pronouns' },
  { en: 'they (three or more)', tr: 'rātou', cat: 'pronouns' },
  { en: 'they two', tr: 'rāua', cat: 'pronouns' },
  { en: 'we (three+, not you)', tr: 'mātou', cat: 'pronouns' },
  { en: 'we all (three+, including you)', tr: 'tātou', cat: 'pronouns' },
  { en: 'you two', tr: 'kōrua', cat: 'pronouns' },
  { en: 'you all (three+)', tr: 'koutou', cat: 'pronouns' },
  { en: 'what', tr: 'aha', cat: 'questions' },
  { en: 'who', tr: 'wai', cat: 'questions' },
  { en: 'where', tr: 'hea', cat: 'questions' },
  { en: 'when (future)', tr: 'āhea', cat: 'questions' },
  { en: 'when (past)', tr: 'nōnahea', cat: 'questions' },
  { en: 'how / what like', tr: 'pēhea', cat: 'questions' },
  { en: 'how many', tr: 'hia', cat: 'questions' },
  { en: 'eat / food', tr: 'kai', cat: 'verbs' },
  { en: 'sleep', tr: 'moe', cat: 'verbs' },
  { en: 'go / travel', tr: 'haere', cat: 'verbs' },
  { en: 'return / also', tr: 'hoki', cat: 'verbs' },
  { en: 'sit / stay / live', tr: 'noho', cat: 'verbs' },
  { en: 'speak / talk', tr: 'kōrero', cat: 'verbs' },
  { en: 'listen', tr: 'whakarongo', cat: 'verbs' },
  { en: 'look', tr: 'titiro', cat: 'verbs' },
  { en: 'work / do', tr: 'mahi', cat: 'verbs' },
  { en: 'learn / teach', tr: 'ako', cat: 'verbs' },
  { en: 'love / care', tr: 'aroha', cat: 'verbs' },
  { en: 'stand', tr: 'tū', cat: 'verbs' },
  { en: 'run', tr: 'oma', cat: 'verbs' },
  { en: 'turn', tr: 'huri', cat: 'verbs' },
  { en: 'give (to me)', tr: 'homai', cat: 'verbs' },
  { en: 'know / understand', tr: 'mōhio', cat: 'verbs' },
  { en: 'see / find', tr: 'kite', cat: 'verbs' },
  { en: 'past tense marker', tr: 'i', cat: 'particles' },
  { en: 'narrative / sequential tense marker', tr: 'ka', cat: 'particles' },
  { en: 'ongoing action suffix', tr: 'ana', cat: 'particles' },
  { en: 'again / still / also', tr: 'anō', cat: 'particles' },
  { en: 'gently / carefully', tr: 'āta', cat: 'particles' },
  { en: 'understand / clear / bright', tr: 'mārama', cat: 'verbs' },
  { en: 'unwell / sick', tr: 'māuiui', cat: 'descriptors' },
  { en: 'year / to settle / count', tr: 'tau', cat: 'nouns' },
  { en: 'teacher', tr: 'kaiako', cat: 'nouns' },
  { en: 'student / learner', tr: 'ākonga', cat: 'nouns' },
  { en: 'England', tr: 'Ingarani', cat: 'nouns' },
  { en: 'custom / meaning / protocol', tr: 'tikanga', cat: 'nouns' },
  { en: 'want / desire', tr: 'hiahia', cat: 'verbs' },
  { en: 'now / at this moment', tr: 'ināianei', cat: 'particles' },
  { en: 'tomorrow', tr: 'āpōpō', cat: 'particles' },
  { en: 'yesterday', tr: 'inanahi', cat: 'particles' },
  { en: 'alas! / oh no!', tr: 'auē', cat: 'basics' },
  { en: 'heart / innermost feelings', tr: 'ngākau', cat: 'nouns' },
  { en: 'greet / acknowledge / tribute', tr: 'mihi', cat: 'verbs' },
  { en: 'very / extremely', tr: 'tino', cat: 'particles' },
  { en: 'appearance / somewhat / about', tr: 'āhua', cat: 'particles' },
  { en: 'just / only / freely / without reason', tr: 'noa', cat: 'particles' },
  { en: 'sorry / excuse me / forgive me', tr: 'aroha mai', cat: 'sentences' },
  { en: 'how are you?', tr: 'kei te pēhea koe?', cat: 'sentences' },
  { en: "I'm very well", tr: 'kei te pai rawa atu au', cat: 'sentences' },
  { en: "I'm pretty good", tr: 'kei te āhua pai au', cat: 'sentences' },
  { en: "I'm unwell / sick", tr: 'kei te māuiui au', cat: 'sentences' },
  { en: 'how old are you?', tr: 'e hia ō tau?', cat: 'sentences' },
  { en: 'I am ___ years old', tr: 'e ___ ōku tau', cat: 'sentences' },
  { en: 'what is your job?', tr: 'he aha tō mahi?', cat: 'sentences' },
  { en: 'I am a teacher', tr: 'he kaiako au', cat: 'sentences' },
  { en: 'I am a student', tr: 'he ākonga au', cat: 'sentences' },
  { en: 'I am from England', tr: 'nō Ingarani au', cat: 'sentences' },
  { en: 'I live in ___', tr: 'e noho ana au i ___', cat: 'sentences' },
  { en: "I don't understand", tr: 'kāore au i te mārama', cat: 'sentences' },
  { en: 'do you understand?', tr: 'kei te mārama koe?', cat: 'sentences' },
  { en: 'please say that again', tr: 'tēnā, kōrero anō', cat: 'sentences' },
  { en: 'speak slowly please', tr: 'āta kōrero mai', cat: 'sentences' },
  { en: 'what does ___ mean?', tr: 'he aha te tikanga o ___?', cat: 'sentences' },
  { en: 'I am learning te reo Māori', tr: 'kei te ako au i te reo Māori', cat: 'sentences' },
  { en: 'no worries / it\'s nothing', tr: 'kāore he aha', cat: 'sentences' },
  { en: 'excellent! / very good!', tr: 'tino pai!', cat: 'sentences' },
  { en: "let's eat", tr: 'me kai tātou', cat: 'sentences' },
  { en: 'what do you want?', tr: 'he aha tāu e hiahia ana?', cat: 'sentences' },
  { en: 'give me that', tr: 'homai tēnā', cat: 'sentences' },
  { en: "I don't want it", tr: 'kāore au e hiahia ana', cat: 'sentences' },
  { en: 'today', tr: 'i tēnei rā', cat: 'sentences' },
  { en: 'where is ___?', tr: 'kei hea ___?', cat: 'sentences' },
  { en: 'my heart is very happy', tr: 'ka nui te hari o tōku ngākau', cat: 'sentences' },
  { en: 'my regards / much love', tr: 'he nui ake ōku mihi', cat: 'sentences' },
  { en: 'finished / ended', tr: 'mutu', cat: 'particles' },
  { en: 'my (ō class: people, places, feelings)', tr: 'tōku', cat: 'possessives' },
  { en: 'your (ō class: one person)', tr: 'tōu', cat: 'possessives' },
  { en: 'my (ā class: actions, objects)', tr: 'tāku', cat: 'possessives' },
  { en: 'your (ā class: one person)', tr: 'tāu', cat: 'possessives' },
  { en: 'red', tr: 'whero', cat: 'colours' },
  { en: 'yellow', tr: 'kōwhai', cat: 'colours' },
  { en: 'green', tr: 'kākāriki', cat: 'colours' },
  { en: 'blue', tr: 'kikorangi', cat: 'colours' },
  { en: 'white', tr: 'mā', cat: 'colours' },
  { en: 'black', tr: 'mangu', cat: 'colours' },
  { en: 'orange', tr: 'karaka', cat: 'colours' },
  { en: 'brown', tr: 'kākaka', cat: 'colours' },
  { en: 'pink', tr: 'māwhero', cat: 'colours' },
  { en: 'purple', tr: 'pāpura', cat: 'colours' },
  { en: 'awesome / excellent / fantastic', tr: 'rawe', cat: 'descriptors' },
  { en: 'night', tr: 'pō', cat: 'nouns' },
  { en: 'moonlit / reflected moonlight', tr: 'atarau', cat: 'nouns' },
  { en: 'rippling / agitated (as water)', tr: 'pōkarekare', cat: 'descriptors' },
  { en: 'all / everyone / everything', tr: 'katoa', cat: 'particles' },
  { en: 'daytime / world / dawn', tr: 'ao', cat: 'nouns' },
  { en: 'morning / dawn', tr: 'ata', cat: 'nouns' },
  { en: 'afternoon / evening', tr: 'ahiahi', cat: 'nouns' },
  { en: 'still / always / continuously', tr: 'tonu', cat: 'particles' },
  { en: 'already / different / instead', tr: 'kē', cat: 'particles' },
  { en: 'away from speaker', tr: 'atu', cat: 'particles' },
  { en: 'upward', tr: 'ake', cat: 'particles' },
  { en: 'downward', tr: 'iho', cat: 'particles' },
  { en: 'towards speaker', tr: 'mai', cat: 'particles' },
  { en: 'but / however', tr: 'engari', cat: 'particles' },
  { en: 'and then / and so', tr: 'ā', cat: 'particles' },
  { en: 'therefore / so / that\'s why', tr: 'nā reira', cat: 'particles' },
  { en: 'body', tr: 'tinana', cat: 'body' },
  { en: 'head', tr: 'upoko', cat: 'body' },
  { en: 'face / eye', tr: 'kanohi', cat: 'body' },
  { en: 'ear', tr: 'taringa', cat: 'body' },
  { en: 'mouth', tr: 'waha', cat: 'body' },
  { en: 'hand / arm', tr: 'ringa', cat: 'body' },
  { en: 'foot / leg', tr: 'waewae', cat: 'body' },
  { en: 'breath / heart / lungs', tr: 'manawa', cat: 'body' },
  { en: 'nose', tr: 'ihu', cat: 'body' },
  { en: 'triangle', tr: 'tapatoru', cat: 'shapes' },
  { en: 'square / rectangle', tr: 'tapawhā', cat: 'shapes' },
  { en: 'circle', tr: 'porohīta', cat: 'shapes' },
  { en: 'star', tr: 'whetu', cat: 'shapes' },
  { en: 'oval / ellipse', tr: 'porotītaha', cat: 'shapes' },
  { en: 'house / building', tr: 'whare', cat: 'nouns' },
  { en: 'home / village', tr: 'kāinga', cat: 'nouns' },
  { en: 'place', tr: 'wāhi', cat: 'nouns' },
  { en: 'land', tr: 'whenua', cat: 'nouns' },
  { en: 'sea / ocean', tr: 'moana', cat: 'nouns' },
  { en: 'river', tr: 'awa', cat: 'nouns' },
  { en: 'mountain', tr: 'maunga', cat: 'nouns' },
  { en: 'forest', tr: 'ngahere', cat: 'nouns' },
  { en: 'sky / day', tr: 'rangi', cat: 'nouns' },
  { en: 'sun / day / sail', tr: 'rā', cat: 'nouns' },
  { en: 'moon / month', tr: 'marama', cat: 'nouns' },
  { en: 'water', tr: 'wai', cat: 'nouns' },
  { en: 'fire', tr: 'ahi', cat: 'nouns' },
  { en: 'person', tr: 'tangata', cat: 'nouns' },
  { en: 'man', tr: 'tāne', cat: 'nouns' },
  { en: 'woman', tr: 'wahine', cat: 'nouns' },
  { en: 'children', tr: 'tamariki', cat: 'nouns' },
  { en: 'child', tr: 'tamaiti', cat: 'nouns' },
  { en: 'family', tr: 'whānau', cat: 'nouns' },
  { en: 'tribe / people', tr: 'iwi', cat: 'nouns' },
  { en: 'subtribe', tr: 'hapū', cat: 'nouns' },
  { en: 'name', tr: 'ingoa', cat: 'nouns' },
  { en: 'language / voice', tr: 'reo', cat: 'nouns' },
  { en: 'canoe / vehicle', tr: 'waka', cat: 'nouns' },
  { en: 'good', tr: 'pai', cat: 'descriptors' },
  { en: 'bad', tr: 'kino', cat: 'descriptors' },
  { en: 'big / many', tr: 'nui', cat: 'descriptors' },
  { en: 'small', tr: 'iti', cat: 'descriptors' },
  { en: 'long / tall', tr: 'roa', cat: 'descriptors' },
  { en: 'short', tr: 'poto', cat: 'descriptors' },
  { en: 'new', tr: 'hou', cat: 'descriptors' },
  { en: 'old', tr: 'tawhito', cat: 'descriptors' },
  { en: 'beautiful', tr: 'ataahua', cat: 'descriptors' },
  { en: 'strong', tr: 'kaha', cat: 'descriptors' },
  { en: 'tired', tr: 'ngenge', cat: 'descriptors' },
  { en: 'hungry', tr: 'hiakai', cat: 'descriptors' },
  { en: 'thirsty', tr: 'hiainu', cat: 'descriptors' },
  { en: 'happy', tr: 'hari', cat: 'descriptors' },
  { en: 'sad', tr: 'pōuri', cat: 'descriptors' },
  { en: 'correct / right', tr: 'tika', cat: 'descriptors' },
  { en: 'wrong', tr: 'hē', cat: 'descriptors' },
  { en: 'cheeky / playfully mischievous', tr: 'whakatoi', cat: 'descriptors' },
  { en: 'one', tr: 'tahi', cat: 'numbers' },
  { en: 'two', tr: 'rua', cat: 'numbers' },
  { en: 'three', tr: 'toru', cat: 'numbers' },
  { en: 'four', tr: 'whā', cat: 'numbers' },
  { en: 'five', tr: 'rima', cat: 'numbers' },
  { en: 'six', tr: 'ono', cat: 'numbers' },
  { en: 'seven', tr: 'whitu', cat: 'numbers' },
  { en: 'eight', tr: 'waru', cat: 'numbers' },
  { en: 'nine', tr: 'iwa', cat: 'numbers' },
  { en: 'ten', tr: 'tekau', cat: 'numbers' },
  { en: 'zero / void / nothingness', tr: 'kore', cat: 'numbers' },
  { en: 'the (singular)', tr: 'te', cat: 'particles' },
  { en: 'the (plural)', tr: 'ngā', cat: 'particles' },
  { en: 'a / an / some', tr: 'he', cat: 'particles' },
  { en: 'is / identifies', tr: 'ko', cat: 'particles' },
  { en: 'at (present location)', tr: 'kei', cat: 'particles' },
  { en: 'to / towards', tr: 'ki', cat: 'particles' },
  { en: 'from / origin (past)', tr: 'nō', cat: 'particles' },
  { en: 'by / belonging to (recent)', tr: 'nā', cat: 'particles' },
  { en: 'and / with', tr: 'me', cat: 'particles' },
  { en: 'no / not', tr: 'kāore', cat: 'particles' },
  { en: 'is not', tr: 'ehara', cat: 'particles' },
  { en: 'present action: I am eating', tr: 'kei te kai au', cat: 'sentences' },
  { en: 'past action: I went', tr: 'i haere au', cat: 'sentences' },
  { en: 'narrative tense: she went', tr: 'ka haere ia', cat: 'sentences' },
  { en: 'should: we two should go', tr: 'me haere tāua', cat: 'sentences' },
  { en: 'my name is...', tr: 'ko ___ tōku ingoa', cat: 'sentences' },
  { en: 'what is your name?', tr: 'ko wai tōu ingoa?', cat: 'sentences' },
  { en: 'where are you from?', tr: 'nō hea koe?', cat: 'sentences' },
  { en: 'I am from...', tr: 'nō ___ au', cat: 'sentences' },
  { en: "I don't know", tr: 'kāore au e mōhio ana', cat: 'sentences' },
  { en: 'he / she is a good person', tr: 'he tangata pai ia', cat: 'sentences' },
  { en: 'listen here!', tr: 'whakarongo mai!', cat: 'sentences' },
  { en: 'be strong / keep going', tr: 'kia kaha', cat: 'sentences' },
  { en: 'take it easy / go gently', tr: 'āta haere', cat: 'sentences' },
  { en: 'see you', tr: 'ka kite', cat: 'sentences' },
  { en: 'see you again', tr: 'ka kite anō', cat: 'sentences' },
  { en: "it's good / that's fine", tr: 'kei te pai', cat: 'sentences' },
  { en: "I'm tired", tr: 'kei te ngenge au', cat: 'sentences' },
  { en: "I'm hungry", tr: 'kei te hiakai au', cat: 'sentences' },
  { en: 'what are you doing?', tr: 'he aha tāu mahi?', cat: 'sentences' },
  { en: 'I am going to the house', tr: 'kei te haere au ki te whare', cat: 'sentences' },
  { en: 'thank you very much', tr: 'kia ora rawa atu', cat: 'sentences' },
  { en: "it's finished / that's it", tr: 'ka mutu', cat: 'sentences' },
  // Animals
  { en: 'dog', tr: 'kurī', cat: 'nouns' },
  { en: 'cat', tr: 'ngeru', cat: 'nouns' },
  { en: 'pig', tr: 'poaka', cat: 'nouns' },
  { en: 'sheep', tr: 'hipi', cat: 'nouns' },
  { en: 'cow', tr: 'kau', cat: 'nouns' },
  { en: 'horse', tr: 'hōiho', cat: 'nouns' },
  { en: 'chicken / hen', tr: 'heihei', cat: 'nouns' },
  { en: 'bird', tr: 'manu', cat: 'nouns' },
  { en: 'fish', tr: 'ika', cat: 'nouns' },
  { en: 'tūī (native songbird)', tr: 'tūī', cat: 'nouns' },
  { en: 'kea (alpine parrot)', tr: 'kea', cat: 'nouns' },
  { en: 'kererū (native wood pigeon)', tr: 'kererū', cat: 'nouns' },
  { en: 'rabbit', tr: 'rāpeti', cat: 'nouns' },
  { en: 'spider', tr: 'pūngāwerewere', cat: 'nouns' },
  { en: 'rat / mouse', tr: 'kiore', cat: 'nouns' },
  // Food
  { en: 'sweet potato', tr: 'kūmara', cat: 'nouns' },
  { en: 'potato', tr: 'rīwai', cat: 'nouns' },
  { en: 'apple', tr: 'āporo', cat: 'nouns' },
  { en: 'bread', tr: 'parāoa', cat: 'nouns' },
  { en: 'milk', tr: 'miraka', cat: 'nouns' },
  { en: 'sugar', tr: 'huka', cat: 'nouns' },
  { en: 'coffee', tr: 'kawhe', cat: 'nouns' },
  { en: 'tea (the drink)', tr: 'tī', cat: 'nouns' },
  { en: 'meat', tr: 'mīti', cat: 'nouns' },
  { en: 'egg', tr: 'hēki', cat: 'nouns' },
  { en: 'salt', tr: 'tote', cat: 'nouns' },
  { en: 'fruit', tr: 'hua rākau', cat: 'nouns' },
  { en: 'vegetable', tr: 'huawhenua', cat: 'nouns' },
  // Family
  { en: 'father / dad', tr: 'pāpā', cat: 'nouns' },
  { en: 'mother / mum', tr: 'whaea', cat: 'nouns' },
  { en: 'older sibling (same gender)', tr: 'tuakana', cat: 'nouns' },
  { en: 'younger sibling (same gender)', tr: 'teina', cat: 'nouns' },
  { en: "sister (of a male)", tr: 'tuahine', cat: 'nouns' },
  { en: 'brother (of a female)', tr: 'tungāne', cat: 'nouns' },
  { en: 'elderly man / grandfather', tr: 'koroua', cat: 'nouns' },
  { en: 'elderly woman / grandmother', tr: 'kuia', cat: 'nouns' },
  { en: 'grandchild', tr: 'mokopuna', cat: 'nouns' },
  { en: 'friend', tr: 'hoa', cat: 'nouns' },
  { en: 'son / boy', tr: 'tama', cat: 'nouns' },
  { en: 'daughter / girl', tr: 'tamāhine', cat: 'nouns' },
  // Weather / nature
  { en: 'rain', tr: 'ua', cat: 'nouns' },
  { en: 'wind', tr: 'hau', cat: 'nouns' },
  { en: 'cloud', tr: 'kapua', cat: 'nouns' },
  { en: 'storm / east wind', tr: 'marangai', cat: 'nouns' },
  // Days of the week
  { en: 'Monday', tr: 'Rāhina', cat: 'days' },
  { en: 'Tuesday', tr: 'Rātū', cat: 'days' },
  { en: 'Wednesday', tr: 'Rāapa', cat: 'days' },
  { en: 'Thursday', tr: 'Rāpare', cat: 'days' },
  { en: 'Friday', tr: 'Rāmere', cat: 'days' },
  { en: 'Saturday', tr: 'Rāhoroi', cat: 'days' },
  { en: 'Sunday', tr: 'Rātapu', cat: 'days' },
  // Verbs
  { en: 'write', tr: 'tuhi', cat: 'verbs' },
  { en: 'read / announce', tr: 'pānui', cat: 'verbs' },
  { en: 'drink', tr: 'inu', cat: 'verbs' },
  { en: 'cry / mourn', tr: 'tangi', cat: 'verbs' },
  { en: 'laugh', tr: 'kata', cat: 'verbs' },
  { en: 'wake up / startle', tr: 'oho', cat: 'verbs' },
  { en: 'ask / question', tr: 'pātai', cat: 'verbs' },
  { en: 'answer / reply', tr: 'whakautu', cat: 'verbs' },
  { en: 'fetch / go and get', tr: 'tiki', cat: 'verbs' },
  { en: 'catch / capture', tr: 'hopu', cat: 'verbs' },
  { en: 'cook / roast', tr: 'tunu', cat: 'verbs' },
  { en: 'wash', tr: 'horoi', cat: 'verbs' },
  { en: 'buy / sell', tr: 'hoko', cat: 'verbs' },
  { en: 'think / thought', tr: 'whakaaro', cat: 'verbs' },
  // Descriptors
  { en: 'hot', tr: 'wera', cat: 'descriptors' },
  { en: 'cold', tr: 'makariri', cat: 'descriptors' },
  { en: 'wet / damp', tr: 'mākūkū', cat: 'descriptors' },
  { en: 'dry', tr: 'maroke', cat: 'descriptors' },
  { en: 'angry', tr: 'riri', cat: 'descriptors' },
  { en: 'shy / embarrassed', tr: 'whakamā', cat: 'descriptors' },
  { en: 'alive / well / healthy', tr: 'ora', cat: 'descriptors' },
  { en: 'easy / gentle / soft', tr: 'ngāwari', cat: 'descriptors' },
  { en: 'difficult / hard', tr: 'uaua', cat: 'descriptors' },
  // Everyday objects / places
  { en: 'book', tr: 'pukapuka', cat: 'nouns' },
  { en: 'chair', tr: 'tūru', cat: 'nouns' },
  { en: 'table', tr: 'tēpu', cat: 'nouns' },
  { en: 'mat / carpet', tr: 'whāriki', cat: 'nouns' },
  { en: 'telephone', tr: 'waea', cat: 'nouns' },
  { en: 'mobile phone', tr: 'waea pūkoro', cat: 'nouns' },
  { en: 'computer', tr: 'rorohiko', cat: 'nouns' },
  { en: 'school', tr: 'kura', cat: 'nouns' },
  { en: 'hospital', tr: 'hōhipera', cat: 'nouns' },
  { en: 'money', tr: 'moni', cat: 'nouns' },
  // Time
  { en: 'week', tr: 'wiki', cat: 'nouns' },
  { en: 'hour', tr: 'hāora', cat: 'nouns' },
  { en: 'minute', tr: 'meneti', cat: 'nouns' },
  // Demonstratives
  { en: 'this (near speaker)', tr: 'tēnei', cat: 'particles' },
  { en: 'that (away from both of us)', tr: 'tērā', cat: 'particles' },
  { en: 'enough! / stop! / well then', tr: 'kāti', cat: 'particles' },
  // Numbers 11-19
  { en: 'eleven', tr: 'tekau mā tahi', cat: 'numbers' },
  { en: 'twelve', tr: 'tekau mā rua', cat: 'numbers' },
  { en: 'thirteen', tr: 'tekau mā toru', cat: 'numbers' },
  { en: 'fourteen', tr: 'tekau mā whā', cat: 'numbers' },
  { en: 'fifteen', tr: 'tekau mā rima', cat: 'numbers' },
  { en: 'sixteen', tr: 'tekau mā ono', cat: 'numbers' },
  { en: 'seventeen', tr: 'tekau mā whitu', cat: 'numbers' },
  { en: 'eighteen', tr: 'tekau mā waru', cat: 'numbers' },
  { en: 'nineteen', tr: 'tekau mā iwa', cat: 'numbers' },
  // Round tens (no individual dictionary audio entry for the bare form)
  { en: 'twenty', tr: 'rua tekau', cat: 'numbers' },
  { en: 'thirty', tr: 'toru tekau', cat: 'numbers' },
  { en: 'forty', tr: 'whā tekau', cat: 'numbers' },
  { en: 'fifty', tr: 'rima tekau', cat: 'numbers' },
  { en: 'sixty', tr: 'ono tekau', cat: 'numbers' },
  { en: 'seventy', tr: 'whitu tekau', cat: 'numbers' },
  { en: 'eighty', tr: 'waru tekau', cat: 'numbers' },
  { en: 'ninety', tr: 'iwa tekau', cat: 'numbers' },
  { en: 'one hundred', tr: 'kotahi rau', cat: 'numbers' },
  // Whakataukī (proverbs), no single-word dictionary audio exists for these
  { en: 'what is the most important thing in the world? it is people, it is people, it is people', tr: 'he aha te mea nui o te ao? he tangata, he tangata, he tangata', cat: 'sentences' },
  { en: 'as the old net withers away, the new net goes fishing (passing the torch to the next generation)', tr: 'ka pū te ruha, ka hao te rangatahi', cat: 'sentences' },
  { en: 'with your food basket and my food basket the people will thrive (working together)', tr: 'nāku te rourou, nāu te rourou, ka ora ai te iwi', cat: 'sentences' },
  { en: 'we are all in this canoe together, with no exception (unity, collective responsibility)', tr: 'he waka eke noa', cat: 'sentences' },
  { en: 'seek the treasure you value most dearly; if you must bow your head, let it be to a lofty mountain (aim high)', tr: 'whāia te iti kahurangi ki te tūohu koe, me he maunga teitei', cat: 'sentences' },

  // ---- Added: te reo tongues expansion (2026-09) ----
  // Greetings (extra)
  { en: 'good morning', tr: 'mōrena', cat: 'greetings' },
  { en: 'good night', tr: 'pō mārie', cat: 'greetings' },
  { en: 'come here / welcome', tr: 'haere mai', cat: 'greetings' },
  { en: 'greetings to us all', tr: 'tēnā tātou katoa', cat: 'greetings' },
  { en: 'a nose-to-nose greeting', tr: 'hongi', cat: 'greetings' },
  { en: 'a handshake', tr: 'harirū', cat: 'greetings' },

  // Basics (extra)
  { en: 'maybe / perhaps', tr: 'pea', cat: 'basics' },
  { en: "that's right / correct", tr: 'koia', cat: 'basics' },
  { en: 'okay / all right', tr: 'ka pai', cat: 'basics' },
  { en: 'really? / is that so?', tr: 'koia rā?', cat: 'basics' },

  // Questions (extra)
  { en: 'which', tr: 'tēhea', cat: 'questions' },
  { en: 'why', tr: 'he aha ai', cat: 'questions' },

  // Verbs
  { en: 'watch', tr: 'mātakitaki', cat: 'verbs' },
  { en: 'play', tr: 'tākaro', cat: 'verbs' },
  { en: 'study / discuss (in a learning forum)', tr: 'wānanga', cat: 'verbs' },
  { en: 'look around / examine', tr: 'tirotiro', cat: 'verbs' },
  { en: 'use', tr: 'whakamahi', cat: 'verbs' },
  { en: 'take / remove', tr: 'tango', cat: 'verbs' },
  { en: 'receive / obtain', tr: 'whiwhi', cat: 'verbs' },
  { en: 'support', tr: 'tautoko', cat: 'verbs' },
  { en: 'help', tr: 'āwhina', cat: 'verbs' },
  { en: 'settle / decide / welcome formally', tr: 'whakatau', cat: 'verbs' },
  { en: 'call out (a ceremonial call)', tr: 'karanga', cat: 'verbs' },
  { en: 'believe', tr: 'whakapono', cat: 'verbs' },
  { en: 'remember / think of', tr: 'mahara', cat: 'verbs' },
  { en: 'forget', tr: 'wareware', cat: 'verbs' },
  { en: 'recall / remember', tr: 'maumahara', cat: 'verbs' },
  { en: 'look after / care for', tr: 'tiaki', cat: 'verbs' },
  { en: 'feed / raise', tr: 'whāngai', cat: 'verbs' },
  { en: 'enter', tr: 'kuhu', cat: 'verbs' },
  { en: 'come out / appear / exit', tr: 'puta', cat: 'verbs' },
  { en: 'attend to / turn to', tr: 'tahuri', cat: 'verbs' },
  { en: 'try / test', tr: 'whakamātau', cat: 'verbs' },
  { en: 'search for', tr: 'rapu', cat: 'verbs' },
  { en: 'look for / seek', tr: 'kimi', cat: 'verbs' },
  { en: 'show / display', tr: 'whakaatu', cat: 'verbs' },
  { en: 'explain', tr: 'whakamārama', cat: 'verbs' },
  { en: 'begin / start', tr: 'tīmata', cat: 'verbs' },
  { en: 'finish / complete (something)', tr: 'whakaoti', cat: 'verbs' },
  { en: 'grow / grow up', tr: 'whakatipu', cat: 'verbs' },
  { en: 'swim', tr: 'kaukau', cat: 'verbs' },
  { en: 'dance', tr: 'kanikani', cat: 'verbs' },
  { en: 'sing', tr: 'waiata', cat: 'verbs' },
  { en: 'ask (request something)', tr: 'tono', cat: 'verbs' },
  { en: 'exchange / swap', tr: 'whakawhiti', cat: 'verbs' },
  { en: 'pull / drag', tr: 'kukume', cat: 'verbs' },
  { en: 'push / push away', tr: 'pana', cat: 'verbs' },
  { en: 'carry (on the back) / broadcast', tr: 'waha', cat: 'verbs' },
  { en: 'climb', tr: 'piki', cat: 'verbs' },
  { en: 'fly', tr: 'rere', cat: 'verbs' },
  { en: 'fall', tr: 'hinga', cat: 'verbs' },
  { en: 'break', tr: 'pakaru', cat: 'verbs' },
  { en: 'release / send / allow', tr: 'tuku', cat: 'verbs' },
  { en: 'add / append', tr: 'tāpiri', cat: 'verbs' },
  { en: 'fix / correct / straighten', tr: 'whakatika', cat: 'verbs' },
  { en: 'wait', tr: 'tatari', cat: 'verbs' },
  { en: 'meet', tr: 'tūtaki', cat: 'verbs' },

  // Particles / grammar words
  { en: 'perfective / already marker', tr: 'kua', cat: 'particles' },
  { en: 'this / right here (emphatic)', tr: 'nei', cat: 'particles' },
  { en: 'linking particle (so that / and then)', tr: 'ai', cat: 'particles' },
  { en: 'for / because of', tr: 'mō', cat: 'particles' },
  { en: 'or', tr: 'rānei', cat: 'particles' },
  { en: 'although / even though', tr: 'ahakoa', cat: 'particles' },
  { en: 'only / just', tr: 'anake', cat: 'particles' },
  { en: 'by / for (future)', tr: 'mā', cat: 'particles' },
  { en: 'in / at / within', tr: 'roto', cat: 'particles' },
  { en: 'a certain / one (indefinite)', tr: 'tētahi', cat: 'particles' },
  { en: 'namely / that is', tr: 'arā', cat: 'particles' },
  { en: 'the aforementioned', tr: 'taua', cat: 'particles' },
  { en: 'a thing / matter', tr: 'mea', cat: 'particles' },
  { en: 'for / at (future time or purpose)', tr: 'hei', cat: 'particles' },
  { en: 'here (this spot)', tr: 'konei', cat: 'particles' },
  { en: 'that (near you)', tr: 'tēnā', cat: 'particles' },
  { en: 'those (aforementioned)', tr: 'ērā', cat: 'particles' },

  // Descriptors
  { en: 'annoyed / fed up', tr: 'hōhā', cat: 'descriptors' },
  { en: 'very angry', tr: 'pukuriri', cat: 'descriptors' },
  { en: 'worried', tr: 'māharahara', cat: 'descriptors' },
  { en: 'joyful', tr: 'koa', cat: 'descriptors' },
  { en: 'afraid', tr: 'mataku', cat: 'descriptors' },
  { en: 'tall / high', tr: 'teitei', cat: 'descriptors' },
  { en: 'different', tr: 'rerekē', cat: 'descriptors' },
  { en: 'sacred / restricted', tr: 'tapu', cat: 'descriptors' },
  { en: 'free of restriction / ordinary', tr: 'noa', cat: 'descriptors' },
  { en: 'free / available', tr: 'wātea', cat: 'descriptors' },
  { en: 'precious / treasured', tr: 'kahurangi', cat: 'descriptors' },
  { en: 'lucky / fortunate', tr: 'waimarie', cat: 'descriptors' },
  { en: 'famous / well-known', tr: 'rongonui', cat: 'descriptors' },
  { en: 'lost', tr: 'ngaro', cat: 'descriptors' },
  { en: 'careful / cautious', tr: 'tūpato', cat: 'descriptors' },
  { en: 'many / numerous', tr: 'maha', cat: 'descriptors' },
  { en: 'plentiful / big (plural)', tr: 'nunui', cat: 'descriptors' },
  { en: 'open', tr: 'tuwhera', cat: 'descriptors' },
  { en: 'full', tr: 'kī', cat: 'descriptors' },
  { en: 'silent / mute', tr: 'ngū', cat: 'descriptors' },
  { en: 'loud / rumbling (of thunder, engines)', tr: 'haruru', cat: 'descriptors' },
  { en: 'clean', tr: 'mā', cat: 'descriptors' },
  { en: 'adult / grown-up', tr: 'pakeke', cat: 'descriptors' },
  { en: 'big / great', tr: 'rahi', cat: 'descriptors' },
  { en: 'fast / quick', tr: 'tere', cat: 'descriptors' },
  { en: 'slow', tr: 'pūhoi', cat: 'descriptors' },
  { en: 'light / easy, also means "mum" (a real double meaning)', tr: 'māmā', cat: 'descriptors' },
  { en: 'safe', tr: 'haumaru', cat: 'descriptors' },

  // Nouns, people / places / culture
  { en: 'thought / idea', tr: 'whakaaro', cat: 'nouns' },
  { en: 'word', tr: 'kupu', cat: 'nouns' },
  { en: 'topic / purpose / agenda', tr: 'kaupapa', cat: 'nouns' },
  { en: 'treasure', tr: 'taonga', cat: 'nouns' },
  { en: 'parents', tr: 'mātua', cat: 'nouns' },
  { en: 'chief / leader', tr: 'rangatira', cat: 'nouns' },
  { en: 'elder (male)', tr: 'kaumātua', cat: 'nouns' },
  { en: 'expert / priest / specialist', tr: 'tohunga', cat: 'nouns' },
  { en: 'god / deity / supernatural being', tr: 'atua', cat: 'nouns' },
  { en: 'spirit', tr: 'wairua', cat: 'nouns' },
  { en: 'prestige / authority / standing', tr: 'mana', cat: 'nouns' },
  { en: 'meeting grounds', tr: 'marae', cat: 'nouns' },
  { en: 'gathering / meeting', tr: 'hui', cat: 'nouns' },
  { en: 'song', tr: 'waiata', cat: 'nouns' },
  { en: 'posture dance / war dance', tr: 'haka', cat: 'nouns' },
  { en: 'genealogy', tr: 'whakapapa', cat: 'nouns' },
  { en: 'region / boundary', tr: 'rohe', cat: 'nouns' },
  { en: 'guardian / caretaker', tr: 'kaitiaki', cat: 'nouns' },
  { en: 'gift / donation', tr: 'koha', cat: 'nouns' },
  { en: 'feast', tr: 'hākari', cat: 'nouns' },
  { en: 'employee / worker', tr: 'kaimahi', cat: 'nouns' },
  { en: 'baby', tr: 'pēpi', cat: 'nouns' },
  { en: 'enemy', tr: 'hoariri', cat: 'nouns' },
  { en: 'summit / peak / standard', tr: 'taumata', cat: 'nouns' },
  { en: 'position / status', tr: 'tūranga', cat: 'nouns' },
  { en: 'discovery / finding', tr: 'kitenga', cat: 'nouns' },
  { en: 'return / homecoming', tr: 'hokinga', cat: 'nouns' },
  { en: 'reason / topic / issue', tr: 'take', cat: 'nouns' },
  { en: 'problem / trouble', tr: 'raruraru', cat: 'nouns' },
  { en: 'time / period', tr: 'wā', cat: 'nouns' },
  { en: 'exhibition / display', tr: 'whakaaturanga', cat: 'nouns' },
  { en: 'photo / image', tr: 'whakaahua', cat: 'nouns' },
  { en: 'picture / photo / movie', tr: 'pikitia', cat: 'nouns' },
  { en: 'example', tr: 'tauira', cat: 'nouns' },
  { en: 'well-being / livelihood', tr: 'oranga', cat: 'nouns' },
  { en: 'holistic health / wellbeing', tr: 'hauora', cat: 'nouns' },
  { en: 'pain', tr: 'mamae', cat: 'nouns' },
  { en: 'breath', tr: 'hā', cat: 'nouns' },
  { en: 'clothing', tr: 'kākahu', cat: 'nouns' },
  { en: 'hat', tr: 'pōtae', cat: 'nouns' },
  { en: 'shoes', tr: 'hū', cat: 'nouns' },
  { en: 'trousers', tr: 'tarau', cat: 'nouns' },
  { en: 'coat / jacket', tr: 'koti', cat: 'nouns' },
  { en: 'blanket', tr: 'paraikete', cat: 'nouns' },
  { en: 'road / path', tr: 'huarahi', cat: 'nouns' },
  { en: 'town / city', tr: 'tāone', cat: 'nouns' },
  { en: 'stone / rock', tr: 'kōhatu', cat: 'nouns' },
  { en: 'lake', tr: 'roto', cat: 'nouns' },
  { en: 'hill', tr: 'puke', cat: 'nouns' },
  { en: 'beach / sand', tr: 'one', cat: 'nouns' },
  { en: 'island', tr: 'motu', cat: 'nouns' },
  { en: 'tide / coast', tr: 'tai', cat: 'nouns' },
  { en: 'wave', tr: 'ngaru', cat: 'nouns' },
  { en: 'lip', tr: 'ngutu', cat: 'nouns' },
  { en: 'teeth', tr: 'niho', cat: 'nouns' },
  { en: 'hair (of the head)', tr: 'makawe', cat: 'nouns' },
  { en: 'eye (alternative term)', tr: 'karu', cat: 'nouns' },
  { en: 'tears', tr: 'roimata', cat: 'nouns' },
  { en: 'cup', tr: 'kapu', cat: 'nouns' },
  { en: 'plate', tr: 'pereti', cat: 'nouns' },
  { en: 'cupboard', tr: 'kāpata', cat: 'nouns' },
  { en: 'bed', tr: 'moenga', cat: 'nouns' },
  { en: 'paper', tr: 'pepa', cat: 'nouns' },
  { en: 'page', tr: 'whārangi', cat: 'nouns' },
  { en: 'basket / kit', tr: 'kete', cat: 'nouns' },
  { en: 'map / plan', tr: 'mahere', cat: 'nouns' },
  { en: 'grandmother (informal)', tr: 'karani', cat: 'nouns' },
  { en: 'lamp / light', tr: 'rama', cat: 'nouns' },
  { en: 'huia (extinct native bird, culturally treasured)', tr: 'huia', cat: 'nouns' },
  { en: 'sign / mark / symbol', tr: 'tohu', cat: 'nouns' },
  { en: 'fear / awe', tr: 'wehi', cat: 'nouns' },
  { en: 'law', tr: 'ture', cat: 'nouns' },
  { en: 'ship', tr: 'kaipuke', cat: 'nouns' },
  { en: 'truck', tr: 'taraka', cat: 'nouns' },
  { en: 'car', tr: 'motokā', cat: 'nouns' },
  { en: 'train', tr: 'tereina', cat: 'nouns' },
  { en: 'aeroplane', tr: 'waka rererangi', cat: 'nouns' },
  { en: 'kiwi (bird)', tr: 'kiwi', cat: 'nouns' },
  { en: 'albatross', tr: 'toroa', cat: 'nouns' },
  { en: 'chick / baby bird', tr: 'pī', cat: 'nouns' },
  { en: 'poi (item used in poi dance)', tr: 'poi', cat: 'nouns' },
  { en: 'greenstone / jade', tr: 'pounamu', cat: 'nouns' },
  { en: 'oil / fat', tr: 'hinu', cat: 'nouns' },
  { en: 'liver / seat of emotion', tr: 'ate', cat: 'nouns' },
  { en: 'stomach / belly', tr: 'puku', cat: 'nouns' },
  { en: 'chest', tr: 'uma', cat: 'nouns' },
  { en: 'happiness / joy', tr: 'harikoa', cat: 'nouns' },
  { en: 'box', tr: 'pouaka', cat: 'nouns' },
  { en: 'television', tr: 'pouaka whakaata', cat: 'nouns' },
  { en: 'radio', tr: 'reo irirangi', cat: 'nouns' },
  { en: 'letter (mail)', tr: 'reta', cat: 'nouns' },
  { en: 'toilet', tr: 'wharepaku', cat: 'nouns' },
  { en: 'journey / trip', tr: 'haerenga', cat: 'nouns' },
  { en: 'autumn', tr: 'ngahuru', cat: 'nouns' },
  { en: 'summer', tr: 'raumati', cat: 'nouns' },
  { en: 'winter', tr: 'hōtoke', cat: 'nouns' },
  { en: 'spring', tr: 'kōanga', cat: 'nouns' },

  // Sentences / conversational
  { en: "what's up? / how's it going?", tr: 'kei te aha koe?', cat: 'sentences' },
  { en: 'nothing much', tr: 'kāore he aha e mahia ana', cat: 'sentences' },
  { en: 'see you tomorrow', tr: 'ka kite āpōpō', cat: 'sentences' },
  { en: 'see you soon', tr: 'ka kite ā tōna wā', cat: 'sentences' },
  { en: 'good morning to you', tr: 'mōrena koe', cat: 'sentences' },
  { en: 'good night, sleep well', tr: 'pō mārie, moe mai', cat: 'sentences' },
  { en: 'where are you going?', tr: 'kei te haere koe ki hea?', cat: 'sentences' },
  { en: 'I am going home', tr: 'kei te haere au ki te kāinga', cat: 'sentences' },
  { en: 'what time is it?', tr: 'e hia te wā?', cat: 'sentences' },
  { en: "it is ___ o'clock", tr: 'ko te ___ o te hāora', cat: 'sentences' },
  { en: 'can you help me?', tr: 'ka taea e koe te āwhina i a au?', cat: 'sentences' },
  { en: 'of course / sure', tr: 'ae mārika', cat: 'sentences' },
  { en: 'I agree', tr: 'e whakaae ana au', cat: 'sentences' },
  { en: 'I disagree', tr: 'kāore au e whakaae ana', cat: 'sentences' },
  { en: 'in my opinion', tr: 'ki tōku whakaaro', cat: 'sentences' },
  { en: 'what do you think?', tr: 'he aha tō whakaaro?', cat: 'sentences' },
  { en: 'it is raining', tr: 'kei te ua', cat: 'sentences' },
  { en: 'it is cold today', tr: 'he makariri te rā nei', cat: 'sentences' },
  { en: 'it is hot today', tr: 'he wera te rā nei', cat: 'sentences' },
  { en: 'how much is this?', tr: 'e hia te utu o tēnei?', cat: 'sentences' },
  { en: 'I would like ___, please', tr: 'e hiahia ana au ki te ___, koa', cat: 'sentences' },
  { en: 'thank you for your help', tr: 'ngā mihi mō tō āwhina', cat: 'sentences' },
  { en: 'no problem at all', tr: 'kāore he raru', cat: 'sentences' },
  { en: 'can I sit here?', tr: 'ka taea e au te noho ki konei?', cat: 'sentences' },
  { en: 'excuse me (to get past)', tr: 'tēnā koa', cat: 'sentences' },
  { en: 'I am proud of you', tr: 'e whakahīhī ana au ki a koe', cat: 'sentences' },
  { en: 'take care', tr: 'kia tūpato', cat: 'sentences' },
  { en: 'be careful', tr: 'āta haere, āta noho', cat: 'sentences' },
  { en: 'congratulations', tr: 'ngā mihi', cat: 'sentences' },
  { en: 'welcome to our home', tr: 'nau mai ki tō mātou kāinga', cat: 'sentences' },
  { en: "let's go", tr: 'haere tāua', cat: 'sentences' },
  { en: 'wait a moment', tr: 'tatari mai', cat: 'sentences' },
  { en: 'come in', tr: 'tomo mai', cat: 'sentences' },
  { en: 'I love you', tr: 'e aroha ana au ki a koe', cat: 'sentences' },
  { en: 'I miss you', tr: 'e ngākau nui ana au ki a koe', cat: 'sentences' },
  { en: 'happy birthday', tr: 'mānawatia tō rā whānau', cat: 'sentences' },
  { en: 'I am married', tr: 'kua marena au', cat: 'sentences' },
  { en: 'I have two children', tr: 'e rua aku tamariki', cat: 'sentences' },
  { en: 'what school did you go to?', tr: 'i haere koe ki tēhea kura?', cat: 'sentences' },
  { en: 'the sun is shining', tr: 'kei te whiti te rā', cat: 'sentences' },
  { en: "I'm happy to meet you", tr: 'kei te harikoa au ki te tūtaki i a koe', cat: 'sentences' },
  { en: "what's the weather like today?", tr: 'he pēhea te rangi i tēnei rā?', cat: 'sentences' },
  { en: 'I need to go now', tr: 'me haere au ināianei', cat: 'sentences' },
  { en: "that's a good question", tr: 'he pātai pai tēnā', cat: 'sentences' },
  { en: 'where is the toilet?', tr: 'kei hea te wharepaku?', cat: 'sentences' },
  { en: "I'm on my way", tr: 'kei te haere mai au', cat: 'sentences' },
  { en: 'have a good day', tr: 'kia pai tō rā', cat: 'sentences' },
  { en: 'have a safe trip', tr: 'kia haumaru tō haerenga', cat: 'sentences' },
  // more whakataukī, verified before inclusion
  { en: 'my strength is not that of an individual, but that of many', tr: 'ehara taku toa i te toa takitahi, engari he toa takitini', cat: 'sentences' },
  { en: 'there is only one eye of the needle through which the white, red and black threads must pass (unity across all peoples)', tr: 'kotahi te kōwhao o te ngira e kuhuna ai te miro mā, te miro whero, te miro pango', cat: 'sentences' },

  // Possessives, plural forms (dual/plural "our")
  { en: 'our (two, not you), ō class', tr: 'tō māua', cat: 'possessives' },
  { en: 'our (two, including you), ō class', tr: 'tō tāua', cat: 'possessives' },
  { en: 'our (three+, not you), ō class', tr: 'tō mātou', cat: 'possessives' },
  { en: 'our (all), ō class', tr: 'tō tātou', cat: 'possessives' },
  { en: 'our (two, not you), ā class', tr: 'tā māua', cat: 'possessives' },
  { en: 'our (two, including you), ā class', tr: 'tā tāua', cat: 'possessives' },
  { en: 'our (three+, not you), ā class', tr: 'tā mātou', cat: 'possessives' },
  { en: 'our (all), ā class', tr: 'tā tātou', cat: 'possessives' },

  // Colours (extra)
  { en: 'grey', tr: 'kiwikiwi', cat: 'colours' },
  { en: 'gold', tr: 'kōura', cat: 'colours' },
  { en: 'silver', tr: 'hiriwa', cat: 'colours' },

  // Body (extra)
  { en: 'abdomen / womb', tr: 'kōpū', cat: 'body' },
  { en: 'skin', tr: 'kiri', cat: 'body' },
  { en: 'bone, also means tribe/people (a real double meaning)', tr: 'iwi', cat: 'body' },
  { en: 'blood', tr: 'toto', cat: 'body' },
  { en: 'neck / throat', tr: 'kakī', cat: 'body' },
  { en: 'shoulder', tr: 'pokohiwi', cat: 'body' },
  { en: 'finger / toe', tr: 'matimati', cat: 'body' },
  { en: 'knee', tr: 'turi', cat: 'body' },

  // Shapes / geometry (extra)
  { en: 'vertical / upright', tr: 'poutū', cat: 'shapes' },
  { en: 'horizontal', tr: 'whakapae', cat: 'shapes' },

  // Numbers (extra, ordinals and larger counts)
  { en: 'first', tr: 'tuatahi', cat: 'numbers' },
  { en: 'second', tr: 'tuarua', cat: 'numbers' },
  { en: 'third', tr: 'tuatoru', cat: 'numbers' },
  { en: 'fourth', tr: 'tuawhā', cat: 'numbers' },
  { en: 'fifth', tr: 'tuarima', cat: 'numbers' },
  { en: 'one thousand', tr: 'kotahi mano', cat: 'numbers' },
  { en: 'two hundred', tr: 'rua rau', cat: 'numbers' },
  { en: 'three hundred', tr: 'toru rau', cat: 'numbers' },
  { en: 'many / countless', tr: 'tini', cat: 'numbers' },
  { en: 'a pair / couple', tr: 'tokorua', cat: 'numbers' },

  // Months of the year, traditional Māori month names (filed under 'days'
  // alongside the weekdays, since they share the same calendar/reference use)
  { en: 'January', tr: 'Kohitātea', cat: 'days' },
  { en: 'February', tr: 'Huitanguru', cat: 'days' },
  { en: 'March', tr: 'Poutūterangi', cat: 'days' },
  { en: 'April', tr: 'Paengawhāwhā', cat: 'days' },
  { en: 'May', tr: 'Haratua', cat: 'days' },
  { en: 'June', tr: 'Pipiri', cat: 'days' },
  { en: 'July', tr: 'Hōngongoi', cat: 'days' },
  { en: 'August', tr: 'Here-turi-kōkā', cat: 'days' },
  { en: 'September', tr: 'Mahuru', cat: 'days' },
  { en: 'October', tr: 'Whiringa-ā-nuku', cat: 'days' },
  { en: 'November', tr: 'Whiringa-ā-rangi', cat: 'days' },
  { en: 'December', tr: 'Hakihea', cat: 'days' },

  // New category: Tikanga & Marae
  { en: 'ceremonial welcome onto a marae', tr: 'pōwhiri', cat: 'tikanga' },
  { en: 'a formal welcome speech', tr: 'mihi whakatau', cat: 'tikanga' },
  { en: 'prayer / incantation / blessing', tr: 'karakia', cat: 'tikanga' },
  { en: 'life force / vital essence', tr: 'mauri', cat: 'tikanga' },
  { en: 'hospitality / care for others', tr: 'manaakitanga', cat: 'tikanga' },
  { en: 'unity / solidarity', tr: 'kotahitanga', cat: 'tikanga' },
  { en: 'the process of relationship-building', tr: 'whanaungatanga', cat: 'tikanga' },
  { en: 'meeting house', tr: 'wharenui', cat: 'tikanga' },
  { en: 'dining hall', tr: 'wharekai', cat: 'tikanga' },
  { en: "the speakers' bench at the front of a meeting house", tr: 'paepae', cat: 'tikanga' },
  { en: 'orator / speaker', tr: 'kaikōrero', cat: 'tikanga' },
  { en: 'group of visitors', tr: 'manuhiri', cat: 'tikanga' },
  { en: 'host people / local people', tr: 'tangata whenua', cat: 'tikanga' },
  { en: 'culture', tr: 'ahurea', cat: 'tikanga' },
  { en: 'custom handed down through generations', tr: 'tuku iho', cat: 'tikanga' },
  { en: 'respect', tr: 'whakaute', cat: 'tikanga' },
  { en: 'working together / cooperation', tr: 'mahi tahi', cat: 'tikanga' },
  { en: 'the rites and rituals of mourning for the dead', tr: 'tangihanga', cat: 'tikanga' },
  { en: 'formal speech / oratory', tr: 'whaikōrero', cat: 'tikanga' },
  { en: 'lament / traditional song of mourning', tr: 'waiata tangi', cat: 'tikanga' },
  { en: 'action song', tr: 'waiata-ā-ringa', cat: 'tikanga' },
  { en: 'a traditional short club-like weapon', tr: 'patu', cat: 'tikanga' },
  { en: 'carved ancestral figure', tr: 'tekoteko', cat: 'tikanga' },
  { en: 'carving', tr: 'whakairo', cat: 'tikanga' },
  { en: 'a traditional woven cloak', tr: 'kākahu', cat: 'tikanga' },
  { en: 'traditional facial or body tattoo', tr: 'tā moko', cat: 'tikanga' },
  { en: 'language nest / early-childhood language immersion', tr: 'kōhanga reo', cat: 'tikanga' },
  { en: 'Māori-medium immersion primary school', tr: 'kura kaupapa Māori', cat: 'tikanga' },
  { en: 'guardianship / stewardship of the environment', tr: 'kaitiakitanga', cat: 'tikanga' },
  { en: 'the Māori worldview', tr: 'te ao Māori', cat: 'tikanga' },
  { en: 'chieftainship / sovereignty', tr: 'rangatiratanga', cat: 'tikanga' },
  { en: 'self-determination (a key Te Tiriti o Waitangi concept)', tr: 'tino rangatiratanga', cat: 'tikanga' },
  { en: 'reciprocity / cost / balance owed (a core tikanga concept)', tr: 'utu', cat: 'tikanga' },
  { en: 'psychic force / power / vitality', tr: 'ihi', cat: 'tikanga' },

  // A few extra everyday words to round the set out
  { en: 'prepare / arrange', tr: 'whakarite', cat: 'verbs' },
  { en: 'fix up / improve / bless', tr: 'whakapai', cat: 'verbs' },
  { en: 'celebrate / honour / make much of', tr: 'whakanui', cat: 'verbs' },
  { en: 'lay out / set down', tr: 'whakatakoto', cat: 'verbs' },
  { en: 'return / give back', tr: 'whakahoki', cat: 'verbs' },
  { en: 'business', tr: 'pakihi', cat: 'nouns' },
  { en: 'fund / money pool', tr: 'pūtea', cat: 'nouns' },
  { en: 'resources / property', tr: 'rawa', cat: 'nouns' },
  { en: 'hotel', tr: 'hōtēra', cat: 'nouns' },
  { en: 'warrior / brave person', tr: 'toa', cat: 'nouns' },
  { en: 'successful', tr: 'angitu', cat: 'descriptors' },
  { en: 'weak / feeble', tr: 'ngoikore', cat: 'descriptors' },
  { en: 'strong / firm / mature', tr: 'pakari', cat: 'descriptors' },
  { en: 'like this / in this way', tr: 'pēnei', cat: 'particles' },
  { en: 'like that', tr: 'pērā', cat: 'particles' },
  { en: 'after / behind', tr: 'i muri', cat: 'particles' },
  { en: 'before / in front', tr: 'i mua', cat: 'particles' },
  { en: 'there it is / behold', tr: 'anā', cat: 'basics' },
  { en: 'whose / by whom', tr: 'nā wai', cat: 'questions' },
]

const seen = new Set<string>()
export const ALL_CARDS: Card[] = CARDS_RAW
  .filter(c => {
    const key = `${c.tr}|${c.cat}`
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
  .map(c => ({ ...c, id: `${toSlug(c.tr)}-${c.cat}` }))

export const DECKS: Record<string, Card[]> = {
  all: ALL_CARDS,
  vocab: ALL_CARDS.filter(c => ['nouns', 'verbs', 'descriptors'].includes(c.cat)),
  sentences: ALL_CARDS.filter(c => c.cat === 'sentences'),
  possessives: ALL_CARDS.filter(c => c.cat === 'possessives'),
  colours: ALL_CARDS.filter(c => c.cat === 'colours'),
  shapes: ALL_CARDS.filter(c => c.cat === 'shapes'),
  body: ALL_CARDS.filter(c => c.cat === 'body'),
  particles: ALL_CARDS.filter(c => c.cat === 'particles'),
  pronouns: ALL_CARDS.filter(c => c.cat === 'pronouns'),
  numbers: ALL_CARDS.filter(c => c.cat === 'numbers'),
  days: ALL_CARDS.filter(c => c.cat === 'days'),
  tikanga: ALL_CARDS.filter(c => c.cat === 'tikanga'),
}
